<?php
$tableau_variable['devoirs'] = Array(
  "id" =>           Array( "type" => "single",
					                 "nom" => "id",
					                 "obligatoire" => "0",
					                 "longueur" => "20"),
  "id_prof" =>      Array( "type" => "single",
					                 "nom" => "id_prof",
					                 "obligatoire" => "0",
					                 "longueur" => "5"),
  "id_classe" =>     Array("type" => "single",
					                 "nom" => "id_classe",
					                 "obligatoire" => "0",
					                 "longueur" => "5"),
  "id_niveau" =>    Array( "type" => "single",
					                 "nom" => "id_niveau",
					                 "obligatoire" => "0",
					                 "longueur" => "10"),
  "id_matiere" =>   Array( "type" => "liste_classe",
								           "nom" => "id_matiere",
								           "obligatoire" => "0",
								           "longueur" => "10",
								           "nomliste" => "matieres_cj"),
  "date_donnee" =>  Array( "type" => "date",
								           "obligatoire" => "1",
								           "nom" => "date_donnee"),
  "date_faire" =>   Array( "type" => "date",
								           "obligatoire" => "1",
								           "nom" => "date_faire"),
  "contenu" =>      Array( "type" => "texte",
								           "obligatoire" => "0",
		                       "largeur" => "100",
		                       "hauteur" => "7",
		                       "nom" => "contenu"),
  "id_seance" =>    Array( "type" => "single",
					                 "nom" => "id_seance",
					                 "obligatoire" => "0",
					                 "longueur" => "20"),
);
?>