<?php
$tableau_variable['email'] = Array(
  "id" => 				      Array( "type" => "single",
								     "nom" => "id",
								     "obligatoire" => "0",
								     "longueur" => "50"),
  "id_expediteur" => 		  Array( "type" => "single",
								     "nom" => "id_expediteur",
								     "obligatoire" => "0",
								     "longueur" => "20"),
  "type_expediteur" => 		  Array( "type" => "single",
								     "nom" => "type_expediteur",
								     "obligatoire" => "0",
								     "longueur" => "1"),
  "id_destinataire" => 		  Array( "type" => "single",
								     "nom" => "id_destinataire",
								     "obligatoire" => "0",
								     "longueur" => "20"),
  "id_dossier_exp" =>         Array( "type" => "liste",
									 "nom" => "id_dossier_exp",
								     "obligatoire" => "0",
								     "nomliste" => "dossiers"),
  "etat" =>                   Array( "type" => "liste",
									 "nom" => "etat",
								     "obligatoire" => "1",
								     "nomliste" => "etat_email"),
  "titre" => 				  Array( "type" => "varchar_long",
								     "nom" => "titre",
								     "majuscule"=>"0",
								     "obligatoire" => "1",
								     "longueur" => "255"),
  "messagerie" => Array( "type" => "editeur",
												"placer" => "1",
												"obligatoire" => "0",
								     "largeur" => "125",
								     "hauteur" => "25",
								     "nom" => "messagerie"),
  "date" => 	Array( "type" => "dateheure",
								     "nom" => "date",
								     "obligatoire" => "0"),
);

$tableau_recherche['email'] = Array(
  "date" => 	Array( "type" => "date",
								     "nom" => "date",
										 "tabindex"=>"1",
								     "recherche" => "1"),
  "expediteur" => Array( 	"type" => "varchar",
													"nom" => "expediteur",
										 "tabindex"=>"3",
													"recherche"=>"2",
													"longueur" => "255"),
  "destinataire" => Array("type" => "varchar",
													"nom" => "destinataire",
										 "tabindex"=>"4",
													"recherche"=>"4",
													"longueur" => "255"),
  "titre" => 	Array( "type" => "varchar",
								     "nom" => "titre",
										 "tabindex"=>"2",
								     "recherche"=>"5",
								     "longueur" => "255")
);
?>