<?php
$tableau_variable['cahier'] = Array(
  "id" =>           Array( "type" => "single",
					                 "nom" => "id",
					                 "obligatoire" => "0",
					                 "longueur" => "20"),
  "id_prof" =>      Array( "type" => "single",
					                 "nom" => "id_prof",
					                 "obligatoire" => "0",
					                 "longueur" => "5"),
  "id_classe" =>     Array("type" => "single",
					                 "nom" => "id_classe",
					                 "obligatoire" => "0",
					                 "longueur" => "5"),
  "id_niveau" =>    Array( "type" => "single",
					                 "nom" => "id_niveau",
					                 "obligatoire" => "0",
					                 "longueur" => "10"),
  "id_matiere" =>   Array( "type" => "liste_classe",
								           "nom" => "id_matiere",
								           "obligatoire" => "0",
								           "longueur" => "10",
													 "tabindex" => "3",
								           "plus"=>"RECRE|".$Langue['LBL_RECREATION'],
								           "nomliste" => "matieres_cj"),
  "date" =>         Array( "type" => "date",
								           "obligatoire" => "1",
								           "nom" => "date"),
  "heure_debut" =>  Array( "type" => "single",
					                 "nom" => "heure_debut",
					                 "obligatoire" => "0",
					                 "longueur" => "8"),
  "heure_fin" =>    Array( "type" => "single",
					                 "nom" => "heure_fin",
					                 "obligatoire" => "0",
					                 "longueur" => "8"),
  "contenu" =>  Array( "type" => "editeur",
								                 "obligatoire" => "1",
								                 "largeur" => "100",
								                 "hauteur" => "10",
																 "placer" => "1",
																 "tabindex" => "8",
								                 "nom" => "contenu"),
  "parent" =>     Array( "type" => "editeur",
								                 "obligatoire" => "0",
								                 "largeur" => "100",
								                 "hauteur" => "7",
																 "placer" => "0",
																 "tabindex" => "9",
								                 "nom" => "parent"),
  "objectifs" =>          Array( "type" => "texte",
								                 "obligatoire" => "0",
								                 "largeur" => "100",
								                 "hauteur" => "4",
																 "tabindex" => "6",
								                 "nom" => "objectifs"),
  "materiel" =>           Array( "type" => "texte",
								                 "obligatoire" => "0",
								                 "largeur" => "100",
								                 "hauteur" => "4",
																 "tabindex" => "7",
								                 "nom" => "materiel"),
);

$tableau_variable['devoirs'] = Array(
  "id" =>           Array( "type" => "single",
					                 "nom" => "id",
					                 "obligatoire" => "0",
					                 "longueur" => "20"),
  "id_prof" =>      Array( "type" => "single",
					                 "nom" => "id_prof",
					                 "obligatoire" => "0",
					                 "longueur" => "5"),
  "id_classe" =>     Array("type" => "single",
					                 "nom" => "id_classe",
					                 "obligatoire" => "0",
					                 "longueur" => "5"),
  "id_niveau" =>    Array( "type" => "single",
					                 "nom" => "id_niveau",
					                 "obligatoire" => "0",
					                 "longueur" => "10"),
  "id_matiere" =>   Array( "type" => "liste_classe",
								           "nom" => "id_matiere",
								           "obligatoire" => "0",
								           "longueur" => "10",
													 "tabindex" => "3",
								           "nomliste" => "matieres_cj"),
  "date_donnee" =>  Array( "type" => "date",
								           "obligatoire" => "1",
													 "tabindex" => "4",
								           "nom" => "date_donnee"),
  "date_faire" =>   Array( "type" => "date",
								           "obligatoire" => "1",
													 "tabindex" => "5",
								           "nom" => "date_faire"),
  "contenu" =>      Array( "type" => "texte",
								           "obligatoire" => "0",
		                       "largeur" => "100",
		                       "hauteur" => "7",
													 "tabindex" => "6",
		                       "nom" => "contenu"),
  "id_seance" =>    Array( "type" => "single",
					                 "nom" => "id_seance",
					                 "obligatoire" => "0",
					                 "longueur" => "20"),
);
?>