<?php
/**
 * Modèle de traduction de Gest'Ecole
 * Utiliser ce fichier pour traduire la partie Configuration
 * Envoyer l'ensemble des fichiers traduits à doxconception@gmail.com
 */
 
/**
 * Gest'Ecole translation template
 * Use this file to translate the section Configuration
 * Send all the translated files at doxconception@gmail.com
 */
 
/**
 * XXXXX translation
 * @author Translator Name <translator@email.tld>
 * @version 201x-xx-xx
 */

$Langue_Module = Array(
// Page d'index
  'BTN_BIBLIO' => "Bibliothèque d'école / de classe",
  'BTN_BIBLIO2' => "Bibliothèque de classe",
  'BTN_CONFIGURATION_GENERALE' => "Configuration générale de l'application",
  'BTN_COOPERATIVE' => "Coopérative scolaire",
  'BTN_COORDONNEES' => "Coordonnées de votre établissement",
  'BTN_HORAIRES' => "Horaires de votre établissement",
  'BTN_LISTES_CHOIX' => "Listes de choix",
  'BTN_LIVRETS' => "Livrets scolaires",
  'BTN_LOGO' => "Logo de votre établissement",
  'BTN_ONGLETS' => "Onglets accessibles",
  'BTN_MAJ_APPLICATION' => "Mise à jour de l'application",
  'BTN_NETTOYAGE_BDD' => "Nettoyage de la Base de Données",
  'BTN_RESTAURE_BDD' => "Restauration d'une sauvegarde de la BDD",
  'BTN_SAUVE_BDD' => "Sauvegarde de la Base de Données",
  'BTN_VIDER_CACHE' => "Vider le cache de Gest'Ecole",
  'LBL_CONFIGURATION' => "Configuration",
  'LBL_CONFIGURATION_ANNEE_SCOLAIRE' => "Configuration de l'année scolaire",
  'LBL_CONFIGURATION_APPLICATION' => "Configuration de l'application",
  'LBL_DERNIERE_SAUVEGARDE' => "Dernière sauvegarde effectuée le",
  'LBL_DERNIERE_SAUVEGARDE2' => "Dernière sauvegarde effectuée il y a",
  'LBL_INFOS_ETAB' => "Informations sur l'Etablissement",
  'LBL_JOURS' => "jours, le",
  'LBL_MAINTENANCE' => "Maintenance de l'application",

// Etape
  'LBL_ETAPE1' => "Etape 1",
  'LBL_ETAPE2' => "Etape 2",
  'LBL_ETAPE3' => "Etape 3",
  'LBL_ETAPE4' => "Etape 4",
  'LBL_ETAPE5' => "Etape 5",

// Sauvegarde BDD
  'BTN_SAUVEGARDE_BDD' => "Sauvegarder la base de données",
  'BTN_SAUVEGARDE_TELECHARGER' => "Télécharger le fichier généré",
  'LBL_SAUVEGARDE_EXPL1' => "En cliquant sur le bouton <strong>Sauvegarder la base de données</strong>, l'application va générer un fichier ZIP comprenant l'ensemble des données de votre base de données à ce jour et cette heure.",
  'LBL_SAUVEGARDE_EXPL2' => "Téléchargez le fichier et sauvegardez-le précautionneusement sur une clé USB ou un disque dur externe. Il pourrait vous être utile en cas de problème avec l'application.",
  'LBL_SAUVEGARDE_EXPL3' => "Nous vous conseillons de faire une sauvegarde de la base de données :",
  'LBL_SAUVEGARDE_EXPL4' => "Avant et après chaque mise à jour de l'application ;",
  'LBL_SAUVEGARDE_EXPL5' => "Avant la restauration d'une ancienne version de la Base de Données ;",
  'LBL_SAUVEGARDE_EXPL6' => "En fin d'année scolaire ;",
  'LBL_SAUVEGARDE_EXPL7' => "Le plus régulièrement possible (une à deux fois par mois serait un bon rythme)",
  'MSG_SAUVEGARDE_ERREUR_GENERATION' => "Une erreur est survenue lors de la génération du fichier. Merci de bien vouloir recommencer.<br />Si le problème persiste, contactez l\'administrateur de votre réseau pour vérifier que les droits d\'écriture sur le répertoire cache/upload/ sont autorisés.<br />Si cela ne résoud pas le problème, sauvegardez la base de données à l\'aide d\'une application telle phpMyAdmin.",
  'MSG_SAUVEGARDE_GENERATION' => "Génération du fichier en cours...",
  'MSG_SAUVEGARDE_GENERE' => "Le fichier a été généré avec succès. Téléchargez-le en cliquant sur le bouton ci-dessous.",
  
// MAJ Application
  'BTN_MAJ_COMMENCER_VERIF' => "Commencer la vérification",
  'BTN_MAJ_ETAPE2' => "Etape 2 : Sauvegarde de la base de données actuelle",
  'BTN_MAJ_ETAPE4' => "Etape 4 : Vérification de la compatibilité de la mise à jour",
  'BTN_MAJ_ETAPE5' => "Etape 5 : Installation de la mise à jour",
  'BTN_MAJ_UPLOADER' => "Uploader",
  'ERR_MAJ_DEPLACEMENT' => "Une erreur est survenue lors du déplacement du fichier.<br />Merci de contacter un administrateur de l\'application pour vérifier que le dossier cache/update existe et qu\'il est inscriptible.",
  'ERR_MAJ_ECRITURE_FICHIER' => "Erreur lors de l'écriture du fichier",
  'ERR_MAJ_ECRITURE_REPERTOIRE' => "Erreur lors de l'écriture du répertoire",
  'ERR_MAJ_UPLOAD' => "Une erreur est survenue lors de l\'upload du fichier.<br />Merci de contacter un administrateur de l\'application pour vérifier que les fonctions d\'upload sont activées.",
  'LBL_MAJ_AUTRES_DONNEES' => "Autres données mises à jour.",
  'LBL_MAJ_BDD' => "Mise à jour de la base de données effectuée.",
  'LBL_MAJ_COPIE_FICHIER' => "Copie du fichier",
  'LBL_MAJ_COPIE_FICHIERS' => "Copie des fichiers",
  'LBL_MAJ_CREATION_REPERTOIRE' => "Création du répertoire",
  'LBL_MAJ_EXPL1' => "La mise à jour de Gest'&Eacute;cole se passera en 5 étapes :",
  'LBL_MAJ_EXPL2' => "<u>Etape 1</u> : Vous y êtes actuellement. Elle vous explique le processus de mise à jour.",
  'LBL_MAJ_EXPL3' => "<u>Etape 2</u> : Durant cette étape, la base de données actuelle sera sauvegardée et vous pourrez télécharger le fichier généré.",
  'LBL_MAJ_EXPL4' => "<u>Etape 3</u> : Vous devrez indiquer le fichier de mise à jour à uploader.",
  'LBL_MAJ_EXPL5' => "<u>Etape 4</u> : Le fichier est uploadé et est contrôlé pour vérifier qu'il s'applique bien à votre version de Gest'&Eacute;cole.",
  'LBL_MAJ_EXPL6' => "<u>Etape 5</u> : Si le fichier est correct, la mise à jour de Gest'&Eacute;cole se déroule.",
  'LBL_MAJ_EXPL7' => "Vous allez maintenant choisir le fichier de mise à jour. Pour ce faire :",
  'LBL_MAJ_EXPL8' => "Cliquez sur le bouton <strong>Parcourir...</strong> puis choisissez le fichier ZIP à uploader",
  'LBL_MAJ_EXPL9' => "Cliquez sur le bouton <strong>Uploader</strong>. Le fichier sera uploadé et vous passerez à l'étape 4",
  'LBL_MAJ_EXPL10' => "La vérification du fichier de mise à jour peut commencer. Pour ce faire, cliquez sur le bouton <strong>Commencer la vérification</strong>.",
  'LBL_MAJ_FICHIER' => "Fichier de mise à jour",
  'LBL_MAJ_INTERVENTION_TIC' => "Si vous n'êtes pas sûr de vous, contactez un administrateur de votre application (conseiller TICE, ...) pour qu'il vous aide et vous conseille.",
  'LBL_MAJ_TERMINEE' => "La mise à jour de votre application est terminée.<br>Déconnectez-vous puis videz le cache de votre navigateur pour que la mise à jour soit pleinement opérationnelle.",
  'LBL_MAJ_TITRE' => "Mise à jour de Gest'&Eacute;cole",
  'LBL_MAJ_TITRE2' => "Mise à jour de Gest\'&Eacute;cole",
  'MSG_MAJ_CHARGEMENT_FICHIER' => "Chargement du fichier...",
  'MSG_MAJ_DEZIPPAGE' => "Dézippage du fichier en cours...",
  'MSG_MAJ_ERREUR_DEZIPPAGE' => "Une erreur est survenue durant la vérification du fichier : Erreur de dézippage du fichier.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_MAJ_ERREUR_FICHIER' => "Le fichier que vous proposez n\'est pas une archive ZIP. Il ne peut être utilisé pour mettre à jour l\'application.",
  'MSG_MAJ_ERREUR_INSTALL' => "Une erreur est survenue durant la vérification du fichier : Pas de fichier install.txt.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_MAJ_ERREUR_INSTALL_LIRE' => "Une erreur est survenue durant la vérification du fichier : Impossible de lire le fichier install.txt.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_MAJ_ERREUR_PAS_MAJ' => "Une erreur est survenue durant la vérification du fichier : Le fichier n\'est pas un fichier de mise à jour de Gest\'&Eacute;cole.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_MAJ_ERREUR_VERSION' => "Une erreur est survenue durant la vérification du fichier : La version du fichier ne correspond pas à votre version de Gest\'&Eacute;cole.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_MAJ_FICHIER' => "Veuillez indiquez le fichier de mise à jour en cliquant sur le bouton Parcourir...",
  'MSG_MAJ_UPLOAD_OK' => "Le fichier a été uploadé avec succès.",
  'MSG_MAJ_VERIF_FICHIER' => "Vérification du fichier...",
  'MSG_MAJ_PRET_INSTALL' => "Le fichier est correct et peut être installé.",
  
// Restauration BDD
  'BTN_RESTAURATION_COMMENCER' => "Commencer la restauration de la base de données",
  'BTN_RESTAURATION_ETAPE2' => "Etape 2 : Sauvegarde de la base de données actuelle",
  'BTN_RESTAURATION_ETAPE3' => "Etape 3 : Choix du fichier à uploader",
  'BTN_RESTAURATION_ETAPE4' => "Etape 4 : Restauration de la base de données",
  'LBL_RESTAURATION_EXPL1' => "La restauration d'une ancienne version de la base de données peut être utile en cas de problème avec votre base de données actuelle. Celle-ci se passera en 4 étapes :",
  'LBL_RESTAURATION_EXPL2' => "<u>Etape 1</u> : Vous y êtes actuellement. Elle vous explique le processus de restauration.",
  'LBL_RESTAURATION_EXPL3' => "<u>Etape 2</u> : Durant cette étape, la base de données actuelle sera sauvegardée et vous pourrez télécharger le fichier généré.",
  'LBL_RESTAURATION_EXPL4' => "<u>Etape 3</u> : Vous devrez indiquer le fichier de restauration de la base de données à uploader.",
  'LBL_RESTAURATION_EXPL5' => "<u>Etape 4</u> : Le fichier est uploadé puis la restauration de la base de données a lieu.",
  'LBL_RESTAURATION_EXPL6' => "<u>Attention</u> : la restauration d'une ancienne version de la base de données entraînera la destruction de la base actuelle. Cela pourrait engendrer des erreurs notamment si vous avez fait des mises à jour de l'application entre temps.",
  'LBL_RESTAURATION_EXPL7' => "Si vous n'êtes pas sûr de vous, contactez un administrateur de votre application (conseiller TICE, ...) pour qu'il vous aide et vous conseille.",
  'LBL_RESTAURATION_EXPL8' => "Vous allez maintenant choisir le fichier de restauration d'une ancienne base de données. Pour ce faire :",
  'LBL_RESTAURATION_EXPL9' => "Cliquez sur le bouton <strong>Parcourir...</strong> puis choisissez le fichier ZIP à uploader",
  'LBL_RESTAURATION_EXPL10' => "Cliquez sur le bouton <strong>Uploader</strong>. Le fichier sera uploadé et vous passerez à l'étape 4",
  'LBL_RESTAURATION_EXPL11' => "La restauration de l'ancienne version de la base de données peut commencer. Pour ce faire, cliquez sur le bouton <strong>Commencer la restauration de la base de données.",
  'LBL_RESTAURATION_FICHIER_RESTAURE' => "Fichier de la base de données à restaurer",
  'LBL_RESTAURATION_TITRE' => "Restauration d'une ancienne version de la base de données",
  'LBL_RESTAURATION_TITRE2' => "Restauration d\'une ancienne version de la base de données",
  'MSG_RESTAURATION_EN_COURS' => "Restauration de la base de données...",
  'MSG_RESTAURATION_FICHIER' => "Veuillez indiquez le fichier à restaurer en cliquant sur le bouton Parcourir...",
  'MSG_RESTAURATION_ERREUR_DEZIPPAGE' => "Une erreur est survenue durant la restauration du fichier : Erreur lors du dézippage du fichier.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_RESTAURATION_ERREUR_RECONSTRUCTION' => "Une erreur est survenue durant la restauration du fichier : Erreur durant la reconstruction de la base de données.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_RESTAURATION_ERREUR_SQL' => "Une erreur est survenue durant la restauration du fichier : Fichier export_bdd.sql manquant.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_RESTAURATION_OK' => "La restauration de la base de données s\'est déroulée correctement.",
  'MSG_RESTAURATION_PAS_ZIP' => "Le fichier que vous proposez n\'est pas une archive ZIP. Il ne peut être utilisé pour restaurer la base de données.",
  
// Nettoyage BDD
  'BTN_NETTOYAGE_ETAPE2' => "Etape 2 : Sauvegarde de la base de données actuelle",
  'BTN_NETTOYAGE_ETAPE3' => "Etape 3 : Nettoyage de la base de données",
  'BTN_NETTOYAGE_NETTOYER' => "Nettoyer la base de données",
  'LBL_NETTOYAGE_EXPL1' => "Le nettoyage de Gest'&Eacute;cole se passera en 3 étapes :",
  'LBL_NETTOYAGE_EXPL2' => "<u>Etape 1</u> : Vous y êtes actuellement. Elle vous explique le processus de nettoyage.",
  'LBL_NETTOYAGE_EXPL3' => "<u>Etape 2</u> : Durant cette étape, la base de données actuelle sera sauvegardée et vous pourrez télécharger le fichier généré.",
  'LBL_NETTOYAGE_EXPL4' => "<u>Etape 3</u> : Le nettoyage de la base de données commence.",
  'LBL_NETTOYAGE_EXPL5' => "Le nettoyage de la base de données consiste à :",
  'LBL_NETTOYAGE_EXPL6' => "Supprimer tous les élèves étant en 6ème (case <i>Entrée en 6ème</i> cochée) ou ayant 12 ans révolus au premier jour de l'année scolaire.",
  'LBL_NETTOYAGE_EXPL7' => "Supprimer toutes les données de ces élèves (absences et justificatifs, livrets scolaires, ...)",
  'LBL_NETTOYAGE_EXPL8' => "Supprimer toutes les évaluations, compétences et catégories de compétences inutiles.",
  'LBL_NETTOYAGE_EXPL9' => "Supprimer les cahiers-journaux et devoirs de plus de deux ans.",
  'LBL_NETTOYAGE_EXPL10' => "Nous arrivons au moment où la base de données va être nettoyée. Une fois le bouton <b>Nettoyer la base de données</b> cliqué, le nettoyage de la base commencera. Vous ne pourrez pas revenir en arrière. Par conséquent, soyez sûr de ce que vous faîtes.",
  'LBL_NETTOYAGE_EXPL11' => "Si c'est le cas, cliquez sur le bouton <b>Nettoyer la base de données</b>.",
  'LBL_NETTOYAGE_TERMINE' => "Nettoyage de la base de données terminé",
  'MSG_NETTOYAGE_EN_COURS' => "Nettoyage en cours...",

// Personnalisation des listes
  'BTN_LISTES_AJOUTER_INTITULE' => "Ajouter un intitulé",
  'BTN_ENREGISTRER_CREER_INTITULE' => "Enregistrer puis créer un nouvel intitulé",
  'BTN_LISTES_PERSONNALISER' => "Personnaliser",
  'LBL_LISTES_ABREVIATION' => "Abréviation",
  'LBL_LISTES_INTITULE' => "Intitulé",
  'LBL_LISTES_LISTES_DISPO' => "Listes",
  'LBL_LISTES_MODIFIER_INTITULE' => "Modifier un intitulé",
  'LBL_LISTES_PERSONNALISATION' => "Personnalisation",
  'LBL_LISTES_PERSONNALISER_LISTES' => "Personnaliser les listes de choix",
  'LBL_LISTES_SUPPRIMER_INTITULE' => "Supprimer un intitulé d\'une liste",
  'LBL_LISTES_TITRE' => "Listes personnalisables",
  'MSG_LISTES_SUPPRIMER_INTITULE' => "Etes-vous sûr(e) de vouloir supprimer cet intitulé ?",
  'MSG_LISTES_SUPPRIMER_INTITULE2' => "<strong><u>Attention</u> : Cette procédure est irréversible et pourrait causer des erreurs si des éléments sont attachés à cet intitulé.",
  'MSG_LISTES_PERSONNALISATION' => "Vous utilisez actuellement la liste par défaut. Pour la personnaliser, cliquez sur le bouton <i>Personnaliser</i>.",
  'SPAN_LISTES_MODIFIER_INTITULE' => "Modifier l'intitulé",
  'SPAN_LISTES_SUPPRIMER_INTITULE' => "Supprimer l'intitulé",

// Paramétrage des livrets scolaires
  'LBL_LIVRETS_BORNE_INFERIEURE' => "Borne inférieure",
  'LBL_LIVRETS_BORNE_SUPERIEURE' => "Borne supérieure",
  'LBL_LIVRETS_CALCUL_RESULTATS' => "Calcul des résultats dans les livrets scolaires",
  'LBL_LIVRETS_COMPETENCE_MARQUEE' => "Compétence marquée",
  'LBL_LIVRETS_COULEUR_ECRITURE' => "Couleur d'écriture",
  'LBL_LIVRETS_COULEUR_FOND' => "Couleur de fond",
  'LBL_LIVRETS_DERNIERE_EVALUATION' => "Dernière évaluation de la compétence",
  'LBL_LIVRETS_METHODE_CALCUL' => "Méthode de calcul",
  'LBL_LIVRETS_MOYENNE_AVEC_PONDERATION' => "Moyenne avec pondération",
  'LBL_LIVRETS_MOYENNE_CONTROLES_COEFFICIENTES' => "Moyenne en fonction du coefficient de l'évaluation défini par l'enseignant",
  'LBL_LIVRETS_MOYENNE_SANS_PONDERATION' => "Moyenne sans pondération",
  'LBL_LIVRETS_NOTATION' => "Notation des compétences",
  'LBL_LIVRETS_PARAMETRES_LS' => "Définir les paramètres par défaut des livrets scolaires",
  'LBL_LIVRETS_PARAMETRES_LS_PROFS' => "Définir les paramètres des livrets scolaires",
  'LBL_LIVRETS_PERIODE1' => "Période 1",
  'LBL_LIVRETS_PERIODE2' => "Période 2",
  'LBL_LIVRETS_PERIODE3' => "Période 3",
  'LBL_LIVRETS_PERIODE4' => "Période 4",
  'LBL_LIVRETS_PERIODE5' => "Période 5",
  'LBL_LIVRETS_PERIODICITE' => "Périodicité des livrets",
  'LBL_LIVRETS_PUBLICATION' => "Publication des livrets",
  'LBL_LIVRETS_PUBLICATION_PERIODE' => "Chaque période",
  'LBL_LIVRETS_PUBLICATION_TRIMESTRE' => "Chaque trimestre",
  'LBL_LIVRETS_RESULTAT' => "Résultat",
  'LBL_LIVRETS_TAUX_REUSSITE' => "Taux de réussite comprise entre ... et ...",
  'LBL_LIVRETS_TRIMESTRE1' => "Trimestre 1",
  'LBL_LIVRETS_TRIMESTRE2' => "Trimestre 2",
  'LBL_LIVRETS_TRIMESTRE3' => "Trimestre 3",
  'LBL_LIVRETS_DEBUT' => "Début",
  'LBL_LIVRETS_FIN' => "Fin",
  'LBL_LIVRETS_PERIODE_TRIMESTRE' => "Découpage de l'année scolaire",
  
// Paramétrage des onglets
  'LBL_ONGLETS_DIRECTEUR' => "Onglets accessibles au Directeur",
  'LBL_ONGLETS_ENSEIGNANTS' => "Onglets accessibles aux Enseignants",
  'LBL_ONGLETS_PARENTS' => "Onglets accessibles aux Parents d'Elèves",
  'LBL_ONGLETS_TITRE' => "Configurer les onglets accessibles",
  'MSG_ONGLETS_SAUVEGARDER' => "La configuration des onglets a bien été sauvegardée. Elle sera effective à votre prochaine connexion.",

// Coordonnées
  'LBL_COORDONNEES_ADRESSE' => "Adresse",
  'LBL_COORDONNEES_CIRCONSCRIPTION' => "Circonscription",
  'LBL_COORDONNEES_EMAIL' => "E-mail",
  'LBL_COORDONNEES_FAX' => "Fax",
  'LBL_COORDONNEES_INFOS_GENERALES' => "Informations générales",
  'LBL_COORDONNEES_INFOS_SECONDAIRES' => "Informations secondaires",
  'LBL_COORDONNEES_NOM' => "Nom",
  'LBL_COORDONNEES_RNE' => "Numéro RNE",
  'LBL_COORDONNEES_SITE_WEB' => "Site Web",
  'LBL_COORDONNEES_TELEPHONE' => "Téléphone",
  'LBL_COORDONNEES_TELEPHONE2' => "Téléphone 2",
  'LBL_COORDONNEES_TITRE' => "Définir les coordonnées de votre établissement",
  
// Logo
  'BTN_RAFRAICHIR' => "Rafraîchir",
  'ERR_LOGO_DEPLACEMENT' => "Une erreur est survenue lors du déplacement du fichier.<br />Merci de contacter un administrateur de l\'application pour vérifier que le dossier cache existe et qu\'il est inscriptible.",
  'ERR_LOGO_UPLOAD' => "Une erreur est survenue lors de l\'upload du fichier.<br />Merci de contacter un administrateur de l\'application pour vérifier que les fonctions d\'upload sont activées.",
  'EXPL_LOGO' => "Le logo doit être au format JPG, PNG ou GIF. Si la largeur et/ou la hauteur excède 100px, le logo sera automatiquement redimensionné.",
  'LBL_LOGO' => "Logo de votre établissement",
  'LBL_LOGO2' => "Logo à uploader",
  'LBL_LOGO_ACTUEL' => "Logo actuel",
  'LBL_LOGO_SUPPRIMER' => "Suppression du logo de votre établissement",
  'MSG_LOGO_ERREUR_FICHIER' => "Le fichier que vous proposez n\'est pas au format adéquat (*.JPG ou *.PNG). Il ne peut être utilisé comme logo de votre établissement.",
  'MSG_LOGO_SUPPRIMER' => "Etes-vous sûr(e) de vouloir supprimer le logo de votre établissement ?",
  'MSG_LOGO_UPLOAD_OK' => "Le logo a été uploadé avec succès. Appuyez sur le bouton Rafraîchir pour voir le nouveau logo.",

// Horaires
  'BTN_HORAIRES_DEFINIR' => "Définir les paramètres",
  'LBL_HORAIRES_A' => "à",
  'LBL_HORAIRES_AM' => "Après-midi",
  'LBL_HORAIRES_ATTENTION_PROFS' => "<u>ATTENTION</u> : Il s'agit ici de donner les horaires d'ouverture de VOTRE établissement, PAS VOS HORAIRES DE TRAVAIL en tant qu'enseignant.",
  'LBL_HORAIRES_DE' => "De",
  'LBL_HORAIRES_HORAIRES_OUVERTURE' => "Horaires d'ouverture",
  'LBL_HORAIRES_JEUDI' => "Jeudi",
  'LBL_HORAIRES_JOURS_OUVERTURE' => "Jours d'ouverture",
  'LBL_HORAIRES_LUNDI' => "Lundi",
  'LBL_HORAIRES_MARDI' => "Mardi",
  'LBL_HORAIRES_MATIN' => "Matin",
  'LBL_HORAIRES_MERCREDI' => "Mercredi",
  'LBL_HORAIRES_SAMEDI' => "Samedi",
  'LBL_HORAIRES_TITRE' => "Définir les horaires par défaut de votre établissement",
  'LBL_HORAIRES_TITRE_PROFS' => "Définir les horaires de votre établissement",
  'LBL_HORAIRES_VENDREDI' => "Vendredi",
  'LBL_HORAIRES_ZONE' => "Zone",
  'LBL_HORAIRES_ZONE_A' => "<b>Zone A</b> : Caen, Clermont-Ferrand, Grenoble, Lyon, Montpellier, Nancy-Metz, Nantes, Rennes, Toulouse",
  'LBL_HORAIRES_ZONE_B' => "<b>Zone B</b> : Aix-Marseille, Amiens, Besançon, Dijon, Lille, Limoges, Nice, Orléans-Tours, Poitiers, Reims, Rouen, Strasbourg",
  'LBL_HORAIRES_ZONE_C' => "<b>Zone C</b> : Bordeaux, Créteil, Paris, Versailles",
  'LBL_HORAIRES_ZONE_D' => "<b>Corse</b>",
  'LBL_HORAIRES_ZONE_E' => "<b>Guadeloupe</b>",
  'LBL_HORAIRES_ZONE_F' => "<b>Guyane</b>",
  'LBL_HORAIRES_ZONE_G' => "<b>Martinique</b>",
  'LBL_HORAIRES_ZONE_H' => "<b>Mayotte</b>",
  'LBL_HORAIRES_ZONE_I' => "<b>Nouvelle-Calédonie</b>",
  'LBL_HORAIRES_ZONE_J' => "<b>Polynésie Française</b>",
  'LBL_HORAIRES_ZONE_K' => "<b>Réunion</b>",
  'LBL_HORAIRES_ZONE_L' => "<b>Saint-Pierre-et-Miquelon</b>",
  'LBL_HORAIRES_ZONE_M' => "<b>Wallis-et-Futuna</b>",
  'LBL_HORAIRES_ZONE_P' => "<b>Autre</b>",
  'LBL_HORAIRES_ZONE_P_PERSONNALISER' => "Définir les paramètres de l'année scolaire",
  
// Horaires personnalisés
  'LBL_HORAIRES_PERSON_ANNEE_SCOLAIRE' => "L'année scolaire est",
  'LBL_HORAIRES_PERSON_ANNEE_SCOLAIRE2' => "sur une année civile (débute le 1er janvier et se termine le 31 décembre)",
  'LBL_HORAIRES_PERSON_ANNEE_SCOLAIRE3' => "à cheval sur deux années civiles",
  'LBL_HORAIRES_PERSON_DEBUT_AS' => "Début de l'année scolaire",
  'LBL_HORAIRES_PERSON_FIN_AS' => "Fin de l'année scolaire",
  'EXPL_HORAIRES_PERSON_DUREE' => "Si l'année scolaire est à cheval sur deux années civiles, nous vous conseillons de la faire durer 12 mois. Par exemple, si l'année scolaire commence le 1er août, faites-la se terminer le 31 juillet de l'année suivante.",
  
// Bibliothèque
  'LBL_BIBLIO_CLASSE' => "Bibliothèque de classe",
  'LBL_BIBLIO_CLASSE2' => "Votre classe dispose d'une bibliothèque de classe",
  'LBL_BIBLIO_DUREE_EMPRUNT' => "Durée d'emprunt",
  'LBL_BIBLIO_ECOLE' => "Bibliothèque d'école",
  'LBL_BIBLIO_ECOLE2' => "Votre établissement dispose d'une bibliothèque d'école",
  'LBL_BIBLIO_NB_LIVRES_EMPRUNTABLES' => "Nombre de livres qu'un élève peut emprunter en même temps",
  'LBL_BIBLIO_TITRE' => "Définir les paramètres de la bibliothèque d'école et/ou de classe",
  'LBL_BIBLIO_TITRE_PROFS' => "Définir les paramètres de la bibliothèque de classe",
  
// Configuration générale
  'LBL_CONFIG_EMAIL_DEFAUT' => "E-mail par défaut",
  'LBL_CONFIG_INFOS_MESSAGERIE' => "Informations pour la messagerie",
  'LBL_CONFIG_LANGUE_DEFAUT' => "Langue par défaut",
  'LBL_CONFIG_MSG_ACCUEIL' => "Message affiché sur la page de connexion de Gest'Ecole",
  'LBL_CONFIG_MSG_ACCUEIL2' => "Message de la page de connexion",
  'LBL_CONFIG_MSG_EXEMPLE' => "Message reçu par les utilisateurs souhaitant être tenu au courant de l'arrivée d'un nouveau message",
  'LBL_CONFIG_MSG_EXEMPLE2' => "Madame, Mademoiselle, Monsieur,",
  'LBL_CONFIG_MSG_EXEMPLE3' => "Un message vous a été envoyé sur Gest'Ecole.",
  'LBL_CONFIG_MSG_EXEMPLE4' => "Rendez-vous à l'adresse",
  'LBL_CONFIG_MSG_EXEMPLE4BIS' => "pour pouvoir le lire.",
  'LBL_CONFIG_MSG_EXEMPLE5' => "Cordialement",
  'LBL_CONFIG_SIGNATAIRE' => "Signataire",
  'LBL_CONFIG_TITRE' => "Configuration générale de l'application",
  'LBL_CONFIG_URL_GESTECOLE' => "Adresse de Gest'Ecole",
  
// Signatures et appréciations des livrets scolaires et registres d'appel
  'LBL_CONFIG_SIGNATURE' => "Signatures électroniques et appréciations",
  'LBL_CONFIG_ABSENCES' => "Registres d'appel",
  'LBL_CONFIG_LIVRETS' => "Livrets scolaires",
  'LBL_CONFIG_SIGNATURE_ABSENCES' => "Les registres d'appel seront signés en ligne",
  'LBL_CONFIG_SIGNATURE_LIVRETS' => "Les livrets scolaires seront signés en ligne",
  'LBL_CONFIG_APPRECIATION_LIVRETS' => "Les appréciations sont saisies via Gest'Ecole",

// Coopérative scolaire
  'EXPL_COOPERATIVE_POT_COMMUN' => "Les crédits disponibles ne sont pas répartis : chaque classe pioche ce dont elle a besoin dans le pot commun.",
  'EXPL_COOPERATIVE_REPARTITION_CLASSES' => "Les crédits disponibles sont répartis pour tout ou partie dans les différentes classes.",
  'LBL_COOPERATIVE_FONCTIONNEMENT' => "Fonctionnement",
  'LBL_COOPERATIVE_MANDATAIRES' => "Mandataires",
  'LBL_COOPERATIVE_PARAMETRES' => "Paramètres généraux",
  'LBL_COOPERATIVE_POT_COMMUN' => "Pas de répartition dans les classes",
  'LBL_COOPERATIVE_PRESENTE' => "Votre établissement dispose d'une coopérative scolaire",
  'LBL_COOPERATIVE_REPARTITION_CLASSES' => "Chaque classe dispose d'un crédit sur le compte",
  'LBL_COOPERATIVE_REPARTITION_CREDITS' => "Répartition des crédits",
  'LBL_COOPERATIVE_TITRE' => "Configuration de la coopérative scolaire",
  
// Ajout d'un fichier de langue
  'BTN_LANGUE_AJOUT' => "Fichiers de langue",
  'BTN_LANGUE_ETAPE2' => "Etape 2 : Choix du fichier à uploader",
  'BTN_LANGUE_ETAPE3' => "Etape 3 : Vérification de la compatibilité du fichier de langue",
  'BTN_LANGUE_ETAPE4' => "Etape 4 : Installation du fichier de langue",
  'ERR_LANGUE_DEPLACEMENT' => "Une erreur est survenue lors du déplacement du fichier.<br />Merci de contacter un administrateur de l\'application pour vérifier que le dossier cache/update existe et qu\'il est inscriptible.",
  'ERR_LANGUE_UPLOAD' => "Une erreur est survenue lors de l\'upload du fichier.<br />Merci de contacter un administrateur de l\'application pour vérifier que les fonctions d\'upload sont activées.",
  'LBL_LANGUE_EXPL1' => "L'ajout et/ou la mise à jour d'un fichier de langue se passera en 5 étapes :",
  'LBL_LANGUE_EXPL2' => "<u>Etape 1</u> : Vous y êtes actuellement. Elle vous explique le processus.",
  'LBL_LANGUE_EXPL3' => "<u>Etape 2</u> : Vous devrez indiquer le fichier d'ajout et/ou de mise à jour à uploader.",
  'LBL_LANGUE_EXPL4' => "<u>Etape 3</u> : Le fichier est uploadé et est contrôlé pour vérifier qu'il s'agit bien d'un fichier de langue.",
  'LBL_LANGUE_EXPL5' => "<u>Etape 4</u> : Si le fichier est correct, le fichier de langue est installé.",
  'LBL_LANGUE_EXPL6' => "Veuillez choisir le fichier de langue. Pour ce faire :",
  'LBL_LANGUE_EXPL7' => "Cliquez sur le bouton <strong>Parcourir...</strong> puis choisissez le fichier le langue à uploader",
  'LBL_LANGUE_EXPL8' => "Cliquez sur le bouton <strong>Uploader</strong>. Le fichier sera uploadé et vous passerez à l'étape 3",
  'LBL_LANGUE_EXPL9' => "La vérification du fichier de langue peut commencer. Pour ce faire, cliquez sur le bouton <strong>Commencer la vérification</strong>.",
  'LBL_LANGUE_FICHIER' => "Fichier de langue",
  'LBL_LANGUE_TERMINEE' => "Le fichier de langue a été installé avec succès. Déconnectez-vous pour que la langue soit active.",
  'LBL_LANGUE_TITRE' => "Ajouter et/ou mettre à jour un fichier de langue",
  'MSG_LANGUE_ERREUR_FICHIER' => "Le fichier que vous proposez n\'est pas une archive ZIP. Il ne peut être utilisé pour installer le fichier de langue.",
  'MSG_LANGUE_ERREUR_INSTALL' => "Une erreur est survenue durant la vérification du fichier : Pas de fichier install.txt.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_LANGUE_ERREUR_INSTALL_LIRE' => "Une erreur est survenue durant la vérification du fichier : Impossible de lire le fichier install.txt.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_LANGUE_ERREUR_PAS_MAJ' => "Une erreur est survenue durant la vérification du fichier : Le fichier n\'est pas un fichier de langue.<br />Merci de contacter l\'administrateur de votre application et lui signaler l\'erreur.",
  'MSG_LANGUE_FICHIER' => "Veuillez indiquez le fichier de langue en cliquant sur le bouton Parcourir...",  
  
// Champs ajoutés
  'BTN_CONFIGURATION_PHPINFO' => "Voir la configuration PHP",  														// Ajouté le 23/05/2012
  'LBL_OPTIONS_SUPPL' => "Options supplémentaires",  																// Ajouté le 23/05/2012
  'LBL_LISTES_ABREVIATION_COURT' => "Abr.",																			// Ajouté le 29/05/2012
  'LBL_LISTES_NIVEAU' => "Liste des niveaux",																		// Ajouté le 29/05/2012
  'LBL_LISTES_MATIERES_B' => "Liste des matières d'une évaluation",													// Ajouté le 29/05/2012
  'LBL_LISTES_MATIERES_CJ' => "Liste des matières du Cahier-Journal",												// Ajouté le 29/05/2012
  'LBL_LISTES_CATEG_BIBLIO_ECOLE' => "Liste des catégories de livres dans la bibliothèque d'école",					// Ajouté le 29/05/2012
  'LBL_LISTES_CATEG_BIBLIO_CLASSE' => "Liste des catégories de livres dans la bibliothèque de classe",				// Ajouté le 29/05/2012  
	
// Champs ajoutés dans la version 2.1
  'LBL_MAJ_TERMINEE' => "La mise à jour de votre application est terminée.",
  'LBL_MAJ_TERMINEE2' => "A faire pour terminer la mise à jour",
  'LBL_MAJ_TERMINEE3' => "Déconnectez-vous puis videz le cache de votre navigateur pour que la mise à jour soit pleinement opérationnelle.",
	'LBL_CONFIG_DECALAGE' => "Décalage entre l'heure du serveur et l'heure de l'établissement",
	'EXPL_CONFIG_DECALAGE' => "S'il est 12:00 dans votre établissement et que l'heure du serveur est 5:00, sélectionnez -7:00. Pour connaître le décalage, voici l'heure actuelle de votre serveur : ",
	'EXPL_CONFIG_DECALAGE2' => "Comparez avec l'heure actuelle de votre établissement.",
	'LBL_CONFIG_PARAMETRES_GENERAUX' => "Paramètres généraux",
);
?>