<?php
/**
 * Modèle de traduction de Gest'Ecole
 * Utiliser ce fichier pour traduire la partie Coopérative
 * Envoyer l'ensemble des fichiers traduits à doxconception@gmail.com
 */
 
/**
 * Gest'Ecole translation template
 * Use this file to translate the section Cooperative
 * Send all the translated files at doxconception@gmail.com
 */
 
/**
 * XXXXX translation
 * @author Translator Name <translator@email.tld>
 * @version 201x-xx-xx
 */

$Langue_Module = Array(
// Saisie Dépense / Entrée
  'BTN_CREER_TIERS' => "Créer",
  'BTN_OUVRIR_EXERCICE' => "Ouvrir l'exercice",
  'ERR_RAPPROCHEMENT' => "Veuillez cocher au moins une ligne.",
  'ERR_SAISIE_CREDITS_REPARTITION' => "Vous ne pouvez répartir plus de crédits dans les classes que les crédits disponibles.",
  'ERR_SAISIE_OUVERTURE' => "L'exercice n'a pas encore été ouvert par les mandataires.",
  'ERR_SAISIE_OUVERTURE2' => "L'exercice ne peut être ouvert car l'exercice précédent n'a pas été clos.",
  'ERR_SAISIE_OUVERTURE3' => "Le total de l\'actif est différent du total du passif. Veuillez corriger.",
  'EXPL_FONCTIONNEMENT_DATE' => "Indiquez la date à laquelle a lieu l'opération.",
  'EXPL_FONCTIONNEMENT_CLASSE' => "Indiquez la classe concernée par le fonctionnement interne.",
  'EXPL_FONCTIONNEMENT_LIBELLE' => "Indiquez le motif de l'entrée ou de la dépense.",
  'EXPL_FONCTIONNEMENT_MONTANT' => "Indiquez le montant de l'opération.",
  'EXPL_OUVERTURE1' => "L'exercice actuel n'est pas encore ouvert. Pour l'ouvrir, il faut indiquer les montants à la banque, la Banque Postale, dans la caisse ainsi que le montant de l'exercice précédent (appelé Report à nouveau).",
  'EXPL_OUVERTURE2' => "Le montant de l'exercice précédent doit être égal à la somme des montants à la banque, à la Banque Postale et dans la caisse.",
  'EXPL_SAISIE_BANQUE' => "Indiquez ici la banque où sera versé ou débité le montant de l'opération.",
  'EXPL_SAISIE_CLASSE' => "Indiquez la classe concernée par l'entrée ou la dépense.",
  'EXPL_SAISIE_CREDITS_MOTIF' => "Indiquez le motif de la répartition dans les classes.",
  'EXPL_SAISIE_CREDITS_SOMME' => "Indiquez la somme à attribuer à la classe.",
  'EXPL_SAISIE_DATE' => "Indiquez la date à laquelle a lieu l'opération.",
  'EXPL_SAISIE_LIBELLE' => "Indiquez le motif de l'entrée ou de la dépense.",
  'EXPL_SAISIE_LIGNE_COMPTABLE' => "Indiquez la ligne comptable concernée. S'il s'agit d'une entrée, sélectionnez l'une des lignes de comptes de produits. S'il s'agit d'une dépense, sélectionnez l'une des lignes de comptes de charges.",
  'EXPL_SAISIE_MODE_PAIEMENT' => "Indiquez comment l'argent arrive ou sort du compte.",
  'EXPL_SAISIE_MONTANT' => "Indiquez le montant de l'opération. Le montant doit être positif.",
  'EXPL_SAISIE_PIECE_JUSTIFICATIVE' => "Indiquez la pièce qui justifie l'entrée ou la dépense (Entrée : numéro de chèque, de virement, ... - Dépense : numéro de facture, de ticket de caisse).",
  'EXPL_SAISIE_POINTE' => "Lorsque vous recevez un relevé de compte, marquez comme pointé les lignes qui figurent sur le relevé de compte.",
  'EXPL_SAISIE_REF_BANCAIRE' => "Indiquez le numéro du chèque, du virement, ... notamment s'il s'agit d'une dépense.",
  'EXPL_SAISIE_REF_BANCAIRE2' => "Indiquez le numéro du chèque, du virement, ...",
  'EXPL_SAISIE_RELEVE_COMPTE' => "Lors du pointage, indiquez le numéro du relevé du compte où l'opération figure.",
  'EXPL_SAISIE_RELEVE_COMPTE2' => "Indiquez le relevé de compte utilisé pour le rapprochement bancaire.",
  'EXPL_SAISIE_TIERS' => "Indiquez la personne ou société qui verse de l'argent ou à qui on en doit.",
  'EXPL_SAISIE_TIERS_NOM' => "Indiquez le nom du tiers.",
  'EXPL_SAISIE_TIERS_TYPE' => "Indiquez si le tiers est un fournisseur (vous achetez des produits chez lui) ou un client (il vous apporte de l'argent).",
  'EXPL_SAISIE_TRANSFERT_DE' => "Indiquez le compte qui sera débité.",
  'EXPL_SAISIE_TRANSFERT_MOTIF' => "Indiquez le motif du transfert.",
  'EXPL_SAISIE_TRANSFERT_PIECE_JUSTIFICATIVE' => "Indiquez la pièce qui justifie le transfert de fonds.",
  'EXPL_SAISIE_TRANSFERT_VERS' => "Indiquez le compte qui sera crédité.",
  'EXPL_SAISIE_TYPE' => "Indiquez s'il s'agit d'une entrée d'argent ou d'une dépense.",
  'LBL_SAISIE_110' => "110 - Report à nouveau",
  'LBL_SAISIE_512' => "512 - Banque",
  'LBL_SAISIE_514' => "514 - Banque Postale",
  'LBL_SAISIE_530' => "530 - Caisse en espèces",
  'LBL_SAISIE_BANQUE' => "Banque",
  'LBL_SAISIE_BANQUE_CAISSE' => "Banque / Caisse",
  'LBL_SAISIE_BANQUE_MODE' => "Banque / Mode",
  'LBL_SAISIE_CLASSE' => "Classe",
  'LBL_SAISIE_CLIENTS' => "-- CLIENTS --",
  'LBL_SAISIE_COMPTE_BANCAIRE' => "Compte bancaire",
  'LBL_SAISIE_CREDIT' => "Crédit",
  'LBL_SAISIE_CREDITS_DISPO' => "Crédits disponibles",
  'LBL_SAISIE_CREDITS_DISPO_REPARTIS' => "Crédits disponibles / Crédits répartis",
  'LBL_SAISIE_CREDITS_MOTIF' => "Motif de la répartition",
  'LBL_SAISIE_CREDITS_REPARTIS' => "Crédits répartis",
  'LBL_SAISIE_CREDITS_REPARTITION' => "Répartition des crédits",
  'LBL_SAISIE_CREDITS_REPARTITION2' => "Répartition des crédits dans les classes",
  'LBL_SAISIE_CREER_DEPENSE' => "Créer une nouvelle entrée / dépense",
  'LBL_SAISIE_CREER_TIERS' => "Créer un tiers",
  'LBL_SAISIE_DATE' => "Date",
  'LBL_SAISIE_DEBIT' => "Débit",
  'LBL_SAISIE_DEPENSE' => "Dépense",
  'LBL_SAISIE_ENREGISTRER_CREER_DEPENSE' => "Enregistrer puis créer une nouvelle entrée/dépense",
  'LBL_SAISIE_ENTREE' => "Entrée",
  'LBL_SAISIE_EXERCICE' => "Exercice en cours",
  'LBL_SAISIE_FICHE' => "Fiche d'une entrée / dépense",
  'LBL_SAISIE_FICHE_FONCTIONNEMENT_INTERNE' => "Fiche d'un fonctionnement interne",
  'LBL_SAISIE_FICHE_OUVERTURE' => "Fiche d'une ouverture d'exercice",
  'LBL_SAISIE_FICHE_TRANSFERT' => "Fiche d'un transfert de compte à compte",
  'LBL_SAISIE_FOURNISSEURS' => "-- FOURNISSEURS --",
  'LBL_SAISIE_LIBELLE' => "Libellé",
  'LBL_SAISIE_LIGNE_COMPTABLE' => "Ligne comptable",
  'LBL_SAISIE_MODE_PAIEMENT' => "Mode de paiement",
  'LBL_SAISIE_MODE_PAIEMENT2' => "Mode",
  'LBL_SAISIE_MODIFIER_DEPENSE' => "Modifier la fiche d'une entrée / dépense",
  'LBL_SAISIE_MODIFIER_FONCTIONNEMENT_INTERNE' => "Modifier la fiche d'un fonctionnement interne",
  'LBL_SAISIE_MODIFIER_OUVERTURE_EXERCICE' => "Modifier la fiche d'une ouverture d'exercice",
  'LBL_SAISIE_MODIFIER_TRANSFERT' => "Modifier la fiche d'un transfert de compte à compte",
  'LBL_SAISIE_MONTANT' => "Montant",
  'LBL_SAISIE_OUVERTURE' => "Coopérative scolaire : Ouverture d'exercice",
  'LBL_SAISIE_PIECE_JUSTIFICATIVE' => "Pièce justificative",
  'LBL_SAISIE_POINTAGE' => "Pointage des lignes",
  'LBL_SAISIE_POINTE' => "Pointé",
  'LBL_SAISIE_POT_COMMUN' => "-- Pot commun --",
  'LBL_SAISIE_POT_COMMUN2' => "Pot commun",
  'LBL_SAISIE_RAPPROCHEMENT_BANCAIRE' => "Rapprochement bancaire",
  'LBL_SAISIE_REF_BANCAIRE' => "Référence bancaire",
  'LBL_SAISIE_RELEVE_COMPTE' => "Relevé de compte",
  'LBL_SAISIE_SORTIE' => "Sortie",
  'LBL_SAISIE_TIERS' => "Tiers",
  'LBL_SAISIE_TIERS_CLIENT' => "Client",
  'LBL_SAISIE_TIERS_FOURNISSEUR' => "Fournisseur",
  'LBL_SAISIE_TIERS_NOM' => "Nom",
  'LBL_SAISIE_TIERS_TYPE' => "Type",
  'LBL_SAISIE_TOTAL_ACTIF' => "Total Actif",
  'LBL_SAISIE_TOTAL_PASSIF' => "Total PAssif",
  'LBL_SAISIE_TRANSFERT_DE' => "Transfert du compte",
  'LBL_SAISIE_TRANSFERT_VERS' => "Vers le compte",
  'LBL_SAISIE_TYPE' => "Type",
  'LBL_SAISIE_VISUEL' => "Visuel",

// Balance
  'LBL_BALANCE' => "Balance des comptes",
  'LBL_BALANCE2' => "Coopérative scolaire : Balance des comptes",
  'LBL_BALANCE_MONTANT_CREDIT' => "Montant Crédit",
  'LBL_BALANCE_MONTANT_DEBIT' => "Montant Débit",
  'LBL_BALANCE_SOLDE_CREDIT' => "Solde Crédit",
  'LBL_BALANCE_SOLDE_DEBIT' => "Solde Débit",

// Bilan comptable
  'BTN_BILAN_ARRETE_CAISSE' => "Saisir le contenu de la caisse en espèces",
  'BTN_CLORE_BILAN' => "Clore l'exercice comptable",
  'BTN_IMPRIMER_BILAN' => "Imprimer le bilan comptable",
  'LBL_BILAN_ARRETE_CAISSE' => "Arrêté de caisse au 31 août",
  'LBL_BILAN_ARRETE_CAISSE2' => "La caisse n'étant pas un compte bancaire, les sommes indiquées doivent être vérifiées par deux personnes non mandataires :",
  'LBL_BILAN_ACTIF' => "ACTIF",
  'LBL_BILAN_BANQUE_512' => "Compte bancaire 512",
  'LBL_BILAN_BANQUE_512_2' => "Le mandataire de la coopérative ou le foyer doit fournir la copie d'un relevé de compte bancaire où figure le solde indiqué en 512. Si ce dernier ne correspond pas à l'extrait, il doit compléter le tableau (rapprochement bancaire) ci-dessous :",
  'LBL_BILAN_BANQUE_514' => "Compte bancaire 514",
  'LBL_BILAN_BANQUE_514_2' => "Le mandataire de la coopérative ou le foyer doit fournir la copie d'un relevé de compte bancaire où figure le solde indiqué en 514. Si ce dernier ne correspond pas à l'extrait, il doit compléter le tableau (rapprochement bancaire) ci-dessous :",
  'LBL_BILAN_BILLETS' => "BILLETS",
  'LBL_BILAN_CHARGES' => "CHARGES",
  'LBL_BILAN_CHEQUE' => "N° de chèque",
  'LBL_BILAN_CLORE_EXERCICE' => "Clore l'exercice comptable",
  'LBL_BILAN_COMPTABLE' => "Bilan comptable",
  'LBL_BILAN_COMPTABLE_EXERCICE' => "Bilan comptable de l'exercice",
  'LBL_BILAN_DATE_OPERATIONS' => "Date des opérations",
  'LBL_BILAN_DESTINATAIRES' => "Destinataires des chèques<br>ou origine des versements",
  'LBL_BILAN_FONCTIONNEMENT' => "Compte de fonctionnement général du 1<sup>er</sup> septembre",
  'LBL_BILAN_FONCTIONNEMENT2' => " au 31 août",
  'LBL_BILAN_MONTANTS' => "Montants<br>(+/-)",
  'LBL_BILAN_NOMBRE' => "Nombre",
  'LBL_BILAN_PASSIF' => "PASSIF",
  'LBL_BILAN_PETITE_MONNAIE' => "Petite monnaie",
  'LBL_BILAN_PIECES' => "PI&Egrave;CES",
  'LBL_BILAN_PRODUITS' => "PRODUITS",
  'LBL_BILAN_RAPPROCHEMENT_BANCAIRE' => "Rapprochement bancaire",
  'LBL_BILAN_RESULTAT_ANNEE' => "Résultat de l'année",
  'LBL_BILAN_SAISIE_530' => "Saisie du compte 530 - Caisse en espèces",
  'LBL_BILAN_SIMPLIFIE' => "Bilan simplifié au 31 août",
  'LBL_BILAN_SOLDE_512' => "Solde indiqué dans le bilan en compte 512",
  'LBL_BILAN_SOLDE_514' => "Solde indiqué dans le bilan en compte 514",
  'LBL_BILAN_SOLDE_530' => "Solde indiqué au compte 530",
  'LBL_BILAN_SOLDE_ARRETE' => "Solde de l'arrêté de caisse",
  'LBL_BILAN_SOLDE_RELEVE' => "Solde indiqué sur le relevé bancaire fourni",
  'LBL_BILAN_SOMME' => "Somme",
  'LBL_BILAN_TOTAL' => "Total",
  'LBL_BILAN_TOTAL_ACTIF' => "TOTAL DE L'ACTIF",
  'LBL_BILAN_TOTAL_CHARGES' => "TOTAL DES CHARGES (A)",
  'LBL_BILAN_TOTAL_PASSIF' => "TOTAL DU PASSIF",
  'LBL_BILAN_TOTAL_PRODUITS' => "TOTAL DES PRODUITS (B)",
  'LBL_BILAN_VALEUR' => "Valeur",
  'MSG_BILAN_CAISSE' => "Le solde du compte <i>530 - Caisse en espèces</i>",
  'MSG_BILAN_CAISSE2' => "est différent du solde de l\'arrêté de caisse",
  'MSG_BILAN_CAISSE3' => "L\'exercice comptable n\'est donc pas conforme et ne peut être clos.",
  'MSG_BILAN_CLORE' => "Etes-vous sûr(e) de vouloir clore l\'exercice comptable",
  'MSG_BILAN_CLORE2' => "<u>Attention</u> : Cette procédure est irréversible : une fois le bilan clos, vous ne pourrez plus modifier aucune ligne comptable de l\'exercice comptable",
  'MSG_BILAN_PAS_EQUILIBRE' => "Votre bilan comptable n\'est pas équilibré : le total de l\'actif",
  'MSG_BILAN_PAS_EQUILIBRE2' => "est différent du total du passif",
  'MSG_BILAN_PAS_EQUILIBRE3' => "Vérifiez que chaque entrée et sortie d\'argent est bien rattaché à un compte bancaire (512, 514 ou 530).",
  'SQL_BILAN_COMPTABLE' => "Bilan comptable de l\'exercice précédent",
  'SQL_SOLDE_BANQUE' => "Solde à la banque à l\'ouverture d\'exercice",
  'SQL_SOLDE_BANQUE_POSTALE' => "Solde à la Banque Postale à l\'ouverture d\'exercice",
  'SQL_SOLDE_CAISSE' => "Solde de la caisse en espèces à l\'ouverture d\'exercice",
  
// Journal des écritures
  'BTN_JOURNAL_CAISSE_BANQUE' => "Caisse <> Banque",
  'BTN_JOURNAL_RAPPROCHEMENT' => "Rapprochement bancaire",
  'BTN_JOURNAL_REPARTITION' => "Répartir crédits dans les classes",
  'BTN_JOURNAL_SAISIR_OPERATION' => "Saisir une opération",
  'LBL_JOURNAL' => "Journal des écritures",
  'LBL_JOURNAL2' => "Journal des écritures - Exercice",
  'LBL_JOURNAL3' => "Coopérative scolaire : Journal des écritures",
  'LBL_JOURNAL_MODE' => "Transfert",
  'LBL_JOURNAL_SOLDE_COURANT' => "Solde courant",
  'LBL_JOURNAL_SOLDE_POINTE' => "Solde pointé",
  'LBL_JOURNAL_TRANSFERT' => "Transfert compte à compte",
  'LBL_JOURNAL_TRANSFERT_VERS' => "vers",
  'LBL_JOURNAL_SAISIR_DEPENSE' => "Saisir une entrée / dépense",
  'LBL_JOURNAL_SAISIR_TRANSFERT' => "Saisir un transfert de compte à compte",
  'LBL_JOURNAL_SAISIR_REPARTITION' => "Répartition des crédits dans les classes",
  'LBL_JOURNAL_MODIFIER_DEPENSE' => "Modifier la fiche d'une entrée / dépense",
  'LBL_JOURNAL_MODIFIER_TRANSFERT' => "Modifier la fiche d'un transfert compte à compte",
  'LBL_JOURNAL_MODIFIER_REPARTITION' => "Fiche d'une ouverture d'exercice",
  'SPAN_JOURNAL_MODIFIER_FICHE' => "Modifier la fiche",
  'SPAN_JOURNAL_MODIFIER_FICHE_TRANSFERT' => "Modifier la fiche d'un transfert compte à compte",
  'SPAN_JOURNAL_VOIR_FICHE' => "Voir la fiche",
  
// Journal des écritures Classe
  'LBL_JOURNAL_CLASSE' => "Répartition des crédits classe par classe",
  'LBL_JOURNAL_CLASSE2' => "Coopérative scolaire : Répartition des Crédits classe par classe",
  'LBL_JOURNAL_CLASSE_MODE' => "Mode/Banque",
  'LBL_JOURNAL_CLASSE_TOTAL' => "Total",
  
// Grand livre des comptes
  'LBL_GRAND_LIVRE_TITRE' => "Coopérative scolaire : Grand livre des comptes",
  'LBL_GRAND_LIVRE' => "Grand livre des comptes",
  'LBL_GL_CUMUL_CREDIT' => "Cumul Crédit",
  'LBL_GL_CUMUL_DEBIT' => "Cumul Débit",
  'LBL_GL_IMPRESSION_TITRE' => "Grand livre des comptes - Exercice",
  'LBL_GL_MONTANT_CREDIT' => "Montant<br>Crédit",
  'LBL_GL_MONTANT_DEBIT' => "Montant<br>Débit",
  'LBL_GL_PIECE' => "Pièce",
  'LBL_GL_SOLDE_CREDITEUR' => "Solde créditeur",
  'LBL_GL_SOLDE_DEBITEUR' => "Solde débiteur",
  'LBL_GL_TOTAL_COMPTE' => "Total du compte",
  
// Champs ajoutés
  'LBL_COOP_TITRE' => "Coopérative scolaire",									// Ajouté le 23/05/2012
  'MSG_PAS_COOP' => "Pas de coopérative scolaire pour cet exercice.",			// Ajouté le 23/05/2012
	
// Champs ajoutés dans la version 2.1
  'LBL_RECHERCHE_TOUS_CLIENTS' => "-- TOUS LES CLIENTS --",
  'LBL_RECHERCHE_TOUS_FOURNISSEURS' => "-- TOUS LES FOURNISSEURS --",
);
?>