INSERT INTO `config` (`parametre`, `valeur`) VALUES ('langue_defaut', 'en-GB');


INSERT INTO `listes` (`id`, `nom_liste`, `intitule`, `ordre`, `id_prof`) VALUES
('6', 'niveaux', 'Year 4', 6, ''),
('7', 'niveaux', 'Year 5', 7, ''),
('8', 'niveaux', 'Year 6', 8, ''),
('5', 'niveaux', 'Year 3', 5, ''),
('4', 'niveaux', 'Year 2', 4, ''),
('3', 'niveaux', 'Year 1', 3, ''),
('2', 'niveaux', 'Reception', 2, ''),
('1', 'niveaux', 'Nursery', 1, ''),
('26', 'categ_biblio_ecole', 'CD, DVD', 7, ''),
('25', 'categ_biblio_ecole', 'Game Books', 6, ''),
('24', 'categ_biblio_ecole', 'Comics', 5, ''),
('23', 'categ_biblio_ecole', 'Newspapers, Magazines', 4, ''),
('22', 'categ_biblio_ecole', 'Albums', 3, ''),
('21', 'categ_biblio_ecole', 'Documentaries', 2, ''),
('20', 'categ_biblio_ecole', 'Novels', 1, '');


INSERT INTO `etablissement` (`parametre`, `valeur`) VALUES
('couleur0', '#FFFFFF'),
('couleur1', '#FFFFFF'),
('couleur2', '#FFFFFF'),
('couleur3', '#FFFFFF'),
('couleur4', '#FFFFFF'),
('couleur5', '#FFFFFF'),
('couleur6', ''),
('couleur7', ''),
('couleur8', ''),
('couleur9', ''),
('couleur_fond0', '#FF0000'),
('couleur_fond1', '#FF8000'),
('couleur_fond2', '#FFFF00'),
('couleur_fond3', '#FF00FF'),
('couleur_fond4', '#0000FF'),
('couleur_fond5', '#00FF00'),
('couleur_fond6', ''),
('couleur_fond7', ''),
('couleur_fond8', ''),
('couleur_fond9', ''),
('c1', 'E'),
('i1', '30'),
('s1', '40'),
('c2', 'D'),
('i2', '40'),
('s2', '50'),
('c3', 'C'),
('i3', '50'),
('s3', '60'),
('c4', 'B'),
('i4', '60'),
('s4', '80'),
('c5', 'A'),
('i5', '80'),
('s5', '100'),
('c6', ''),
('i6', ''),
('s6', ''),
('c7', ''),
('i7', ''),
('s7', ''),
('c8', ''),
('i8', ''),
('s8', ''),
('c9', ''),
('i9', ''),
('s9', ''),
('c0', 'F'),
('i0', '0'),
('s0', '30');
