<?php
$annee_p=$_SESSION['annee_scolaire']+1;
$tableau_variable['news'] = Array(
  "id" => 				  Array( "type" => "single",
								           "nom" => "id",
								           "obligatoire" => "0",
								           "longueur" => "5"),
  "id_prof" => 		  Array( "type" => "single",
								           "nom" => "id_prof",
								           "obligatoire" => "0",
								           "longueur" => "5"),
  "date" =>         Array( "type" => "date",
							 	           "nom" => "date",
								           "min"=> $_SESSION['annee_scolaire']."0801",
								           "max"=> $annee_p."0731",
                           "obligatoire"=>"1"),
  "cible" =>        Array( "type" => "liste",
                           "obligatoire"=>"0",
                           "nom" => "cible",
						   "nomliste" => "cible_news"),
  "titre" => 	      Array( "type" => "varchar_long",
								       "nom" => "titre",
						               "majuscule"=>"0",
								       "obligatoire" => "1",
								       "longueur" => "255"),
  "contenu" =>      Array( "type" => "editeur",
									 "placer" => "1",
								     "obligatoire" => "0",
								     "largeur" => "100",
								     "hauteur" => "7",
								     "nom" => "contenu")
);

$tableau_variable['taches'] = Array(
  "id" => 			   Array( "type" => "single",
						      "nom" => "id",
						      "obligatoire" => "0",
						      "longueur" => "50"),
  "id_util" => 		   Array( "type" => "single",
						      "nom" => "id_util",
						      "obligatoire" => "0",
						      "longueur" => "20"),
  "type_util" => 	   Array( "type" => "single",
						      "nom" => "type_util",
						      "obligatoire" => "0",
						      "longueur" => "1"),
  "date_echeance" =>   Array( "type" => "date",
						      "nom" => "date_echeance",
                              "obligatoire"=>"0"),
  "heure_echeance" =>  Array( "type" => "heure",
						      "nom" => "heure_echeance",
                              "obligatoire"=>"0"),
  "priorite" =>        Array( "type" => "liste",
                              "obligatoire"=>"0",
                              "nom" => "priorite",
						      "nomliste" => "tache_priorite"),
  "etat" =>            Array( "type" => "liste",
                              "obligatoire"=>"0",
                              "nom" => "etat",
						      "nomliste" => "tache_etat"),
  "titre" => 	       Array( "type" => "varchar_long",
							  "nom" => "titre",
						      "majuscule"=>"0",
							  "obligatoire" => "1",
							  "longueur" => "255"),
  "tache" =>      	   Array( "type" => "texte",
						      "obligatoire" => "0",
						      "largeur" => "100",
						      "hauteur" => "7",
						      "nom" => "tache")
);
?>