<?php
$tableau_variable['agenda'] = Array(
  "id" => 				      Array( "type" => "single",
								     "nom" => "id",
								     "obligatoire" => "0",
								     "longueur" => "15"),
  "id_saisie" => 			  Array( "type" => "single",
								     "nom" => "id_saisie",
								     "obligatoire" => "0",
								     "longueur" => "21"),
  "id_util" => 				  Array( "type" => "single",
								     "nom" => "id_util",
								     "obligatoire" => "0",
								     "longueur" => "15"),
  "resume" => 				  Array( "type" => "varchar_long",
								     "nom" => "resume",
								     "majuscule"=>"0",
								     "obligatoire" => "1",
											"tabindex"=>"1",
								     "longueur" => "255"),
  "date" =>     			  Array( "type" => "date",
								     "obligatoire" => "1",
											"tabindex"=>"2",
								     "nom" => "date"),
  "detail" =>    		  	  Array( "type" => "editeur",
								     "obligatoire" => "0",
								     "largeur" => "100",
									 "placer" => "1",
											"tabindex"=>"7",
								     "hauteur" => "7",
								     "nom" => "detail"),
  "type" =>              	  Array( "type" => "liste",
									 "nom" => "type",
											"tabindex"=>"3",
								     "obligatoire" => "1",
								     "nomliste" => "type_reunion"),
  "heure_debut" =>  	Array( "type" => "heure",
						       "nom" => "heure_debut",
											"tabindex"=>"4",
                               "obligatoire"=>"0"),
  "heure_fin" =>  		Array( "type" => "heure",
						       "nom" => "heure_fin",
											"tabindex"=>"5",
                               "obligatoire"=>"0"),
);
?>