<?php
$tableau_variable['classes'] = Array(
  "id" => 				  Array( "type" => "single",
								           "nom" => "id",
								           "obligatoire" => "0",
								           "longueur" => "64"),
  "nom_classe" => 	Array( "type" => "varchar",
								           "nom" => "nom_classe",
 													 "tabindex" => "1",
						               "majuscule"=>"0",
								           "obligatoire" => "1",
								           "longueur" => "255"),
);

$tableau_recherche['classes'] = Array(
  'nom_classe' => Array('type' => 'varchar',
											  'recherche'=>'1',
												'nom' => 'nom_classe',
												'tabindex'=>'1',
												'longueur' => '255'),
  'nb_eleve' => 	Array('type' => 'varchar',
											  'recherche'=>'2',
												'nom' => 'nb_eleve',
												'tabindex'=>'2',
												'longueur' => '10'),
  'niveaux' => 		Array('type' => 'liste_bdd',
											  'recherche'=>'3',
												'option' => 'valeur',
												'option_vide'=>"1",
												'nom' => 'niveaux',
												'tabindex'=>'3',
												'nomliste' => 'niveaux'),
  'titulaire' => 	Array('type' => 'varchar',
											  'recherche'=>'4',
												'nom' => 'titulaire',
												'tabindex'=>'4',
												'longueur' => '255'),
  'decharge' => 	Array('type' => 'varchar',
											  'recherche'=>'5',
												'nom' => 'decharge',
												'tabindex'=>'5',
												'longueur' => '255'),
  'decloisonnement' => 	Array('type' => 'varchar',
															'recherche'=>'6',
															'nom' => 'decloisonnement',
															'tabindex'=>'6',
															'longueur' => '255'),
  'atsem' => 			Array('type' => 'varchar',
											  'recherche'=>'7',
												'nom' => 'atsem',
												'tabindex'=>'7',
												'longueur' => '255'),
  'intervenants_exterieurs' => 	Array('type' => 'varchar',
																			'recherche'=>'8',
																			'nom' => 'intervenants_exterieurs',
																			'tabindex'=>'8',
																			'longueur' => '255'),
  'autres_intervenants' => 			Array('type' => 'varchar',
																			'recherche'=>'9',
																			'nom' => 'autres_intervenants',
																			'tabindex'=>'9',
																			'longueur' => '255'),
);
?>