<?php
$tableau_variable['eleves'] = Array(
  "id" => 				  Array( "type" => "single",
								           "nom" => "id",
								           "obligatoire" => "0",
								           "longueur" => "128"),
  "nom" => 				  Array( "type" => "varchar",
								           "nom" => "nom",
								           "majuscule"=>"1",
													 "tabindex"=>"1",
								           "obligatoire" => "1",
								           "longueur" => "255"),
  "prenom" => 		  	  Array( "type" => "varchar",
								           "nom" => "prenom",
								           "majuscule"=>"0",
													 "tabindex"=>"2",
								           "obligatoire" => "1",
								           "longueur" => "255"),
  "sexe" =>               Array( "type" => "liste",
										   "nom" => "sexe",
								           "obligatoire" => "1",
													 "tabindex"=>"3",
								           "nomliste" => "sexe"),
  "adresse" =>    		  Array( "type" => "texte",
								           "obligatoire" => "0",
								           "largeur" => "40",
													 "tabindex"=>"5",
								           "hauteur" => "6",
								           "nom" => "adresse"),
  "date_naissance" =>     Array( "type" => "date",
								           "obligatoire" => "1",
													 "tabindex"=>"4",
								           "nom" => "date_naissance"),
  "civilite_pere" =>      Array( "type" => "liste",
										   "nom" => "civilite_pere",
													 "tabindex"=>"6",
								           "obligatoire" => "0",
								           "nomliste" => "civilite"),
  "nom_pere" => 	      Array( "type" => "varchar",
							               "nom" => "nom_pere",
							               "majuscule"=>"1",
													 "tabindex"=>"7",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "prenom_pere" => 		  Array( "type" => "varchar",
							               "nom" => "prenom_pere",
							               "majuscule"=>"0",
													 "tabindex"=>"8",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "adresse_pere" =>    	  Array( "type" => "texte",
							               "obligatoire" => "0",
													 "tabindex"=>"10",
							               "largeur" => "40",
							               "hauteur" => "6",
							               "nom" => "adresse_pere"),
  "tel_pere" => 		  Array( "type" => "varchar",
							               "nom" => "tel_pere",
													 "tabindex"=>"11",
							               "majuscule"=>"0",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "tel2_pere" => 		  Array( "type" => "varchar",
							               "nom" => "tel2_pere",
							               "majuscule"=>"0",
													 "tabindex"=>"12",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "portable_pere" => 	  Array( "type" => "varchar",
							               "nom" => "portable_pere",
							               "majuscule"=>"0",
													 "tabindex"=>"13",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "email_pere" => 	 	  Array( "type" => "email",
							               "nom" => "email_pere",
							               "majuscule"=>"0",
													 "tabindex"=>"14",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "responsable_pere" =>      Array( "type" => "liste",
										   "nom" => "responsable_pere",
													 "tabindex"=>"9",
								           "obligatoire" => "0",
								           "nomliste" => "ouinon"),
  "civilite_mere" =>      Array( "type" => "liste",
										   "nom" => "civilite_mere",
													 "tabindex"=>"16",
								           "obligatoire" => "0",
								           "nomliste" => "civilite"),
  "nom_mere" => 		  Array( "type" => "varchar",
							               "nom" => "nom_mere",
													 "tabindex"=>"17",
							               "majuscule"=>"1",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "nom_jf_mere" => 		  Array( "type" => "varchar",
							               "nom" => "nom_jf_mere",
							               "majuscule"=>"1",
													 "tabindex"=>"18",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "prenom_mere" => 	      Array( "type" => "varchar",
							               "nom" => "prenom_mere",
													 "tabindex"=>"19",
							               "majuscule"=>"0",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "adresse_mere" =>    	  Array( "type" => "texte",
							               "obligatoire" => "0",
													 "tabindex"=>"21",
							               "largeur" => "40",
							               "hauteur" => "6",
							               "nom" => "adresse_mere"),
  "tel_mere" => 		  Array( "type" => "varchar",
							               "nom" => "tel_mere",
							               "majuscule"=>"0",
													 "tabindex"=>"22",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "tel2_mere" => 		  Array( "type" => "varchar",
							               "nom" => "tel2_mere",
													 "tabindex"=>"23",
							               "majuscule"=>"0",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "portable_mere" => 	  Array( "type" => "varchar",
							               "nom" => "portable_mere",
							               "majuscule"=>"0",
													 "tabindex"=>"24",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "email_mere" => 	 	  Array( "type" => "email",
							               "nom" => "email_mere",
							               "majuscule"=>"0",
													 "tabindex"=>"25",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "responsable_mere" =>      Array( "type" => "liste",
										   "nom" => "responsable_mere",
													 "tabindex"=>"20",
								           "obligatoire" => "0",
								           "nomliste" => "ouinon"),
  "recevoir_email_pere" => 	  Array( "type" => "checkbox",
													 "tabindex"=>"15",
								           "nom" => "recevoir_email_pere"),
  "recevoir_email_mere" => 	  Array( "type" => "checkbox",
													 "tabindex"=>"26",
								           "nom" => "recevoir_email_mere"),
  "assurance_rc" => 	  Array( "type" => "varchar",
								           "nom" => "assurance_rc",
								           "majuscule"=>"0",
													 "tabindex"=>"28",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "assurance_ia" => 	  Array( "type" => "varchar",
								           "nom" => "assurance_ia",
													 "tabindex"=>"27",
								           "majuscule"=>"0",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "passe" => 	 	      Array( "type" => "password",
								           "nom" => "passe",
								           "obligatoire" => "0",
													 "tabindex"=>"59",
								           "longueur" => "100"),
  "passe2" => 	 		  Array( "type" => "password",
								           "nom" => "passe2",
													 "tabindex"=>"60",
								           "obligatoire" => "0",
								           "longueur" => "100"),
  "reponse" => 		  	  Array( "type" => "varchar",
								           "nom" => "reponse",
													 "tabindex"=>"62",
								           "majuscule"=>"0",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "questionsecrete" =>   Array( "type" => "liste",
																"nom" => "questionsecrete",
													 "tabindex"=>"61",
																"obligatoire" => "0",
																"nomliste" => "questionsecrete"),
);

$tableau_variable['personnels'] = Array(
  "id" => 				  Array( "type" => "single",
								           "nom" => "id",
								           "obligatoire" => "0",
								           "longueur" => "128"),
  "nom" => 				  Array( "type" => "varchar",
								           "nom" => "nom",
						               "majuscule"=>"1",
													 "tabindex"=>"2",
								           "obligatoire" => "1",
								           "longueur" => "255"),
  "prenom" => 			Array( "type" => "varchar",
								           "nom" => "prenom",
													 "tabindex"=>"3",
						               "majuscule"=>"0",
								           "obligatoire" => "1",
								           "longueur" => "255"),
  "civilite" =>     Array( "type" => "liste",
                           "nom" => "civilite",
													 "tabindex"=>"1",
								           "obligatoire" => "1",
								           "nomliste" => "civilite"),
  "adresse" =>    	Array( "type" => "texte",
								           "obligatoire" => "0",
								           "largeur" => "40",
													 "tabindex"=>"4",
								           "hauteur" => "6",
								           "nom" => "adresse"),
  "tel" => 			    Array( "type" => "varchar",
								           "nom" => "tel",
													 "tabindex"=>"9",
						               "majuscule"=>"0",
								           "obligatoire" => "0",
								           "longueur" => "50"),
  "tel2" => 			  Array( "type" => "varchar",
								           "nom" => "tel2",
						               "majuscule"=>"0",
													 "tabindex"=>"10",
								           "obligatoire" => "0",
								           "longueur" => "50"),
  "portable" => 		Array( "type" => "varchar",
								           "nom" => "portable",
						               "majuscule"=>"0",
													 "tabindex"=>"11",
								           "obligatoire" => "0",
								           "longueur" => "50"),
  "email" => 	 		  Array( "type" => "email",
								           "nom" => "email",
													 "tabindex"=>"12",
						               "majuscule"=>"0",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "nom_conjoint" => 			 Array( "type" => "varchar",
                                  "nom" => "nom_conjoint",
						                      "majuscule"=>"1",
													 "tabindex"=>"15",
								                  "obligatoire" => "0",
								                  "longueur" => "255"),
  "prenom_conjoint" => 		 Array( "type" => "varchar",
                                  "nom" => "prenom_conjoint",
													 "tabindex"=>"16",
						                      "majuscule"=>"0",
								                  "obligatoire" => "0",
                                  "longueur" => "255"),
  "civilite_conjoint" =>   Array( "type" => "liste",
                                  "nom" => "civilite_conjoint",
													 "tabindex"=>"14",
								                  "obligatoire" => "0",
								                  "nomliste" => "civilite"),
  "tel_conjoint" => 			 Array( "type" => "varchar",
								                  "nom" => "tel_conjoint",
													 "tabindex"=>"17",
						                      "majuscule"=>"0",
								                  "obligatoire" => "0",
								                  "longueur" => "50"),
  "tel2_conjoint" => 			 Array( "type" => "varchar",
								                  "nom" => "tel2_conjoint",
						                      "majuscule"=>"0",
													 "tabindex"=>"18",
								                  "obligatoire" => "0",
								                  "longueur" => "50"),
  "port_conjoint" => 		   Array( "type" => "varchar",
								                  "nom" => "port_conjoint",
						                      "majuscule"=>"0",
													 "tabindex"=>"19",
								                  "obligatoire" => "0",
								                  "longueur" => "50"),
  "date_naissance" =>  				Array( "type" => "date",
								           "obligatoire" => "1",
													 "tabindex"=>"5",
								           "nom" => "date_naissance"),
  "recevoir_email" => 	  Array( "type" => "checkbox",
													 "tabindex"=>"13",
								           "nom" => "recevoir_email"),
  "passe" => 	 	      Array( "type" => "password",
								           "nom" => "passe",
													 "tabindex"=>"20",
								           "obligatoire" => "0",
								           "longueur" => "100"),
  "passe2" => 	 		  Array( "type" => "password",
								           "nom" => "passe2",
								           "obligatoire" => "0",
													 "tabindex"=>"21",
								           "longueur" => "100"),
  "date_entree_en" =>  				Array( "type" => "date",
													 "tabindex"=>"6",
								           "obligatoire" => "1",
								           "nom" => "date_entree_en"),
  "date_derniere_inspection" =>  	Array( "type" => "date",
													 "tabindex"=>"7",
								           "obligatoire" => "1",
								           "nom" => "date_derniere_inspection"),
  "echelon" => 					    Array( "type" => "varchar",
								           "nom" => "echelon",
													 "tabindex"=>"8",
										   "majuscule"=>"0",
								           "obligatoire" => "0",
								           "longueur" => "10"),
  "reponse" => 		  	  Array( "type" => "varchar",
								           "nom" => "reponse",
								           "majuscule"=>"0",
													 "tabindex"=>"23",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "questionsecrete" =>   Array( "type" => "liste",
																"nom" => "questionsecrete",
													 "tabindex"=>"22",
																"obligatoire" => "0",
																"nomliste" => "questionsecrete"),
);

?>