<?php
$tableau_variable['cooperative'] = Array(
  "id" => 				  Array( "type" => "single",
								 "nom" => "id",
								 "obligatoire" => "0",
								 "longueur" => "50"),
  "id_classe" => 		  Array( "type" => "single",
								 "nom" => "id_classe",
								 "obligatoire" => "0",
								 "longueur" => "5"),
  "piece" => 	          Array( "type" => "varchar",
								 "nom" => "piece",
						         "majuscule"=>"0",
								 "tabindex"=>"6",
								 "obligatoire" => "1",
								 "longueur" => "255"),
  "libelle" => 	          Array( "type" => "varchar",
								 "nom" => "libelle",
						         "majuscule"=>"0",
								 "tabindex"=>"2",
								 "obligatoire" => "1",
								 "longueur" => "255"),
  "ligne_comptable" =>    Array( "type" => "liste",
								 "nom" => "ligne_comptable",
								 "obligatoire" => "1",
								 "tabindex"=>"3",
								 "nomliste" => "cooperative_ligne"),
  "mode" =>               Array( "type" => "liste",
								 "nom" => "mode",
								 "tabindex"=>"11",
								 "obligatoire" => "1",
								 "nomliste" => "cooperative_mode"),
  "date" =>     		  Array( "type" => "date",
								 "tabindex"=>"1",
								 "obligatoire" => "1",
								 "nom" => "date"),
  "montant" => Array( "type" => "numeraire",
								 "obligatoire" => "1",
								 "tabindex"=>"8",
								 "nom" => "montant"),
  "pointe" =>    		  Array( "type" => "liste",
								 "nom" => "pointe",
								 "obligatoire" => "1",
								 "tabindex"=>"13",
								 "nomliste" => "ouinon"),
  "releve" => 	          Array( "type" => "varchar",
								 "nom" => "releve",
						         "majuscule"=>"0",
								 "tabindex"=>"14",
								 "obligatoire" => "1",
								 "longueur" => "255"),
  "banque" =>    		  Array( "type" => "liste",
								 "nom" => "banque",
								 "tabindex"=>"10",
								 "obligatoire" => "1",
								 "nomliste" => "cooperative_banque"),
  "reference_bancaire" => Array( "type" => "varchar",
								 "nom" => "reference_bancaire",
								 "tabindex"=>"12",
						         "majuscule"=>"0",
								 "obligatoire" => "1",
								 "longueur" => "255"),
  "tiers" => 		  	  Array( "type" => "single",
								 "nom" => "tiers",
								 "obligatoire" => "0",
								 "longueur" => "7"),
);

$tableau_recherche['journal']= Array(
  "date" =>	Array("type" => "date",
									"nom" => "date",
									"tabindex"=> "1",
									"recherche" => "0"),
	"libelle" => Array( "type"=>"varchar",
											"nom"=>"libelle",
											"longueur"=>"255",
									"tabindex"=> "2",
											"recherche"=>"2"),
	"ligne_comptable" => Array( "type"=>"liste",
															"nom"=>"ligne_comptable",
															"recherche"=>"3",
															"nomliste"=>"cooperative_ligne_plus",
															"option"=>"cle",
									"tabindex"=> "3",
															"option_vide"=>"0"),
	"tiers"=>Array("type"=>"varchar",
									"nom"=>"tiers",
									"tabindex"=> "7",
									"recherche"=>"4",
									"longueur"=>"255"),
	"classe"=>Array("type"=>"varchar",
									"nom"=>"classe",
									"tabindex"=> "8",
									"recherche"=>"5",
									"longueur"=>"255"),
	"banque" => Array( "type"=>"liste",
															"nom"=>"banque",
															"recherche"=>"6",
									"tabindex"=> "6",
															"nomliste"=>"cooperative_banque",
															"option"=>"valeur",
															"option_vide"=>"0"),
	"mode" => Array( "type"=>"liste",
															"nom"=>"mode",
															"recherche"=>"7",
															"nomliste"=>"cooperative_mode_recherche",
									"tabindex"=> "9",
															"option"=>"valeur",
															"option_vide"=>"0"),
	"credit"=>Array("type"=>"monetaire",
									"nom"=>"credit",
									"tabindex"=> "4",
									"recherche"=>"8",
									"longueur"=>"10"),
	"debit"=>Array( "type"=>"monetaire",
									"nom"=>"debit",
									"tabindex"=> "5",
									"recherche"=>"9",
									"longueur"=>"10")
);

$tableau_recherche['repartition'] = Array(
  "date" =>	Array("type" => "date",
									"nom" => "date",
									"tabindex"=>'1',
									"recherche" => "0"),
	"libelle" => Array( "type"=>"varchar",
											"nom"=>"libelle",
											"longueur"=>"255",
									"tabindex"=>'2',
											"recherche"=>"2"),
	"ligne_comptable" => Array( "type"=>"liste",
															"nom"=>"ligne_comptable",
															"recherche"=>"3",
															"nomliste"=>"cooperative_ligne_plus",
															"option"=>"cle",
									"tabindex"=>'3',
															"option_vide"=>"0"),
	"tiers"=>Array("type"=>"varchar",
									"nom"=>"tiers",
									"recherche"=>"4",
									"tabindex"=>'4',
									"longueur"=>"255"),
	"banque" => Array( "type"=>"liste",
															"nom"=>"banque",
															"recherche"=>"6",
															"nomliste"=>"cooperative_banque",
									"tabindex"=>'5',
															"option"=>"cle",
															"option_vide"=>"0"),
	"mode" => Array( "type"=>"liste",
															"nom"=>"mode",
															"recherche"=>"7",
									"tabindex"=>'6',
															"nomliste"=>"cooperative_mode_recherche",
															"option"=>"cle",
															"option_vide"=>"0")
);

$tableau_recherche['grandlivre']= Array(
	"categorie"=>Array("type"=>"varchar",
									"nom"=>"categorie",
									"recherche"=>"0",
									"tabindex"=>'3',
									"longueur"=>"255"),
  "date" =>	Array("type" => "date",
									"nom" => "date",
									"tabindex"=>'1',
									"recherche" => "1"),
	"libelle" => Array( "type"=>"varchar",
											"nom"=>"libelle",
											"longueur"=>"255",
									"tabindex"=>'2',
											"recherche"=>"2"),
	"piece" => Array( "type"=>"varchar",
											"nom"=>"piece",
											"longueur"=>"255",
									"tabindex"=>'4',
											"recherche"=>"3"),
	"balance_debit"=>Array( "type"=>"monetaire",
									"nom"=>"balance_debit",
									"recherche"=>"4",
									"tabindex"=>'5',
									"longueur"=>"10"),
	"balance_credit"=>Array("type"=>"monetaire",
									"nom"=>"balance_credit",
									"tabindex"=>'6',
									"recherche"=>"5",
									"longueur"=>"10"),
	"cumul_debit"=>Array( "type"=>"monetaire",
									"nom"=>"cumul_debit",
									"tabindex"=>'7',
									"recherche"=>"6",
									"longueur"=>"10"),
	"cumul_credit"=>Array("type"=>"monetaire",
									"nom"=>"cumul_credit",
									"tabindex"=>'8',
									"recherche"=>"7",
									"longueur"=>"10")
);

$tableau_recherche['balance']= Array(
	"libelle" => Array( "type"=>"varchar",
											"nom"=>"libelle",
											"longueur"=>"255",
											"tabindex"=>"1",
											"recherche"=>"0"),
	"balance_debit"=>Array( "type"=>"monetaire",
									"nom"=>"balance_debit",
									"recherche"=>"1",
											"tabindex"=>"2",
									"longueur"=>"10"),
	"balance_credit"=>Array("type"=>"monetaire",
									"nom"=>"balance_credit",
									"recherche"=>"2",
											"tabindex"=>"3",
									"longueur"=>"10"),
	"solde_debit"=>Array( "type"=>"monetaire",
									"nom"=>"solde_debit",
									"recherche"=>"3",
											"tabindex"=>"4",
									"longueur"=>"10"),
	"solde_credit"=>Array("type"=>"monetaire",
									"nom"=>"solde_credit",
											"tabindex"=>"5",
									"recherche"=>"4",
									"longueur"=>"10")
);
?>