INSERT INTO `config` (`parametre`, `valeur`) VALUES ('langue_defaut', 'fr-FR');


INSERT INTO `cooperative_tiers` (`id`, `nom`) VALUES
('411-001', 'Département'),
('411-002', 'Etat'),
('411-003', 'Mairie'),
('411-004', 'Parents'),
('411-005', 'Région'),
('401-001', 'OCCE');


INSERT INTO `listes` (`id`, `nom_liste`, `intitule`, `ordre`, `id_prof`) VALUES
('6', 'niveaux', 'CE1', 6, ''),
('7', 'niveaux', 'CE2', 7, ''),
('8', 'niveaux', 'CM1', 8, ''),
('9', 'niveaux', 'CM2', 9, ''),
('5', 'niveaux', 'CP', 5, ''),
('4', 'niveaux', 'GS', 4, ''),
('3', 'niveaux', 'MS', 3, ''),
('2', 'niveaux', 'PS', 2, ''),
('1', 'niveaux', 'TPS', 1, ''),
('26', 'categ_biblio_ecole', 'CD, DVD', 7, ''),
('25', 'categ_biblio_ecole', 'Livres de jeux', 6, ''),
('24', 'categ_biblio_ecole', 'Bandes dessinées', 5, ''),
('23', 'categ_biblio_ecole', 'Journaux, Magazines', 4, ''),
('22', 'categ_biblio_ecole', 'Albums', 3, ''),
('21', 'categ_biblio_ecole', 'Documentaires', 2, ''),
('20', 'categ_biblio_ecole', 'Romans Jeunesse', 1, '');


INSERT INTO `etablissement` (`parametre`, `valeur`) VALUES
('couleur0', '#FFFFFF'),
('couleur1', '#FFFFFF'),
('couleur2', '#FFFFFF'),
('couleur3', ''),
('couleur4', ''),
('couleur5', ''),
('couleur6', ''),
('couleur7', ''),
('couleur8', ''),
('couleur9', ''),
('couleur_fond0', '#FF0000'),
('couleur_fond1', '#FF8000'),
('couleur_fond2', '#00FF00'),
('couleur_fond3', ''),
('couleur_fond4', ''),
('couleur_fond5', ''),
('couleur_fond6', ''),
('couleur_fond7', ''),
('couleur_fond8', ''),
('couleur_fond9', ''),
('c1', 'En cours'),
('i1', '35'),
('s1', '70'),
('c2', 'Acquis'),
('i2', '70'),
('s2', '100'),
('c3', ''),
('i3', ''),
('s3', ''),
('c4', ''),
('i4', ''),
('s4', ''),
('c5', ''),
('i5', ''),
('s5', ''),
('c6', ''),
('i6', ''),
('s6', ''),
('c7', ''),
('i7', ''),
('s7', ''),
('c8', ''),
('i8', ''),
('s8', ''),
('c9', ''),
('i9', ''),
('s9', ''),
('c0', 'Non acquis'),
('i0', '0'),
('s0', '35');
