<?php
$tableau_variable['eleves'] = Array(
  "id" => 				  Array( "type" => "single",
								           "nom" => "id",
								           "obligatoire" => "0",
								           "longueur" => "128"),
  "nom" => 				  Array( "type" => "varchar",
								           "nom" => "nom",
								           "majuscule"=>"1",
								           "obligatoire" => "1",
													 "tabindex"=>"1",
								           "longueur" => "255"),
  "prenom" => 		  	  Array( "type" => "varchar",
								           "nom" => "prenom",
								           "majuscule"=>"0",
								           "obligatoire" => "1",
													 "tabindex"=>"2",
								           "longueur" => "255"),
  "sexe" =>               Array( "type" => "liste",
													 "nom" => "sexe",
								           "obligatoire" => "1",
													 "tabindex"=>"3",
								           "nomliste" => "sexe"),
  "adresse" =>    		  Array( "type" => "texte",
								           "obligatoire" => "0",
								           "largeur" => "40",
													 "tabindex"=>"6",
								           "hauteur" => "6",
								           "nom" => "adresse"),
  "date_naissance" =>     Array( "type" => "date",
								           "obligatoire" => "1",
													 "tabindex"=>"4",
								           "nom" => "date_naissance"),
  "lieu_naissance" => 		  	  Array( "type" => "varchar",
								           "nom" => "lieu_naissance",
								           "majuscule"=>"0",
								           "obligatoire" => "1",
													 "tabindex"=>"5",
								           "longueur" => "255"),
  "civilite_pere" =>      Array( "type" => "liste",
													 "nom" => "civilite_pere",
													 "tabindex"=>"10",
								           "obligatoire" => "0",
								           "nomliste" => "civilite"),
  "nom_pere" => 	      Array( "type" => "varchar",
															"nom" => "nom_pere",
															"majuscule"=>"1",
															"tabindex"=>"11",
															"obligatoire" => "0",
															"longueur" => "255"),
  "prenom_pere" => 		  Array( "type" => "varchar",
							               "nom" => "prenom_pere",
							               "majuscule"=>"0",
															"tabindex"=>"12",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "adresse_pere" =>    	  Array( "type" => "texte",
							               "obligatoire" => "0",
															"tabindex"=>"14",
							               "largeur" => "40",
							               "hauteur" => "6",
							               "nom" => "adresse_pere"),
  "tel_pere" => 		  Array( "type" => "varchar",
							               "nom" => "tel_pere",
							               "majuscule"=>"0",
															"tabindex"=>"15",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "tel2_pere" => 		  Array( "type" => "varchar",
							               "nom" => "tel2_pere",
							               "majuscule"=>"0",
															"tabindex"=>"16",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "portable_pere" => 	  Array( "type" => "varchar",
							               "nom" => "portable_pere",
							               "majuscule"=>"0",
															"tabindex"=>"17",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "email_pere" => 	 	  Array( "type" => "email",
							               "nom" => "email_pere",
							               "majuscule"=>"0",
															"tabindex"=>"18",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "responsable_pere" =>      Array( "type" => "liste",
										   "nom" => "responsable_pere",
															"tabindex"=>"13",
								           "obligatoire" => "0",
								           "nomliste" => "ouinon"),
  "civilite_mere" =>      Array( "type" => "liste",
										   "nom" => "civilite_mere",
								           "obligatoire" => "0",
															"tabindex"=>"20",
								           "nomliste" => "civilite"),
  "nom_mere" => 		  Array( "type" => "varchar",
							               "nom" => "nom_mere",
							               "majuscule"=>"1",
															"tabindex"=>"21",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "nom_jf_mere" => 		  Array( "type" => "varchar",
							               "nom" => "nom_jf_mere",
							               "majuscule"=>"1",
															"tabindex"=>"22",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "prenom_mere" => 	      Array( "type" => "varchar",
							               "nom" => "prenom_mere",
							               "majuscule"=>"0",
															"tabindex"=>"23",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "adresse_mere" =>    	  Array( "type" => "texte",
							               "obligatoire" => "0",
							               "largeur" => "40",
															"tabindex"=>"25",
							               "hauteur" => "6",
							               "nom" => "adresse_mere"),
  "tel_mere" => 		  Array( "type" => "varchar",
							               "nom" => "tel_mere",
							               "majuscule"=>"0",
															"tabindex"=>"26",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "tel2_mere" => 		  Array( "type" => "varchar",
							               "nom" => "tel2_mere",
							               "majuscule"=>"0",
															"tabindex"=>"27",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "portable_mere" => 	  Array( "type" => "varchar",
							               "nom" => "portable_mere",
							               "majuscule"=>"0",
															"tabindex"=>"28",
							               "obligatoire" => "0",
							               "longueur" => "50"),
  "email_mere" => 	 	  Array( "type" => "email",
							               "nom" => "email_mere",
															"tabindex"=>"29",
							               "majuscule"=>"0",
							               "obligatoire" => "0",
							               "longueur" => "255"),
  "responsable_mere" =>      Array( "type" => "liste",
										   "nom" => "responsable_mere",
															"tabindex"=>"24",
								           "obligatoire" => "0",
								           "nomliste" => "ouinon"),
  "identifiant" =>   	  Array( "type" => "varchar",
								           "nom" => "identifiant",
						                   "majuscule"=>"0",
															"tabindex"=>"63",
								           "obligatoire" => "0",
								           "longueur" => "100"),
  "passe" => 	 	  	  Array( "type" => "password",
								           "nom" => "passe",
															"tabindex"=>"64",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "assurance_rc" => 	  Array( "type" => "varchar",
								           "nom" => "assurance_rc",
								           "majuscule"=>"0",
															"tabindex"=>"32",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "assurance_ia" => 	  Array( "type" => "varchar",
								           "nom" => "assurance_ia",
								           "majuscule"=>"0",
															"tabindex"=>"31",
								           "obligatoire" => "0",
								           "longueur" => "255"),
  "date_entree" =>        Array( "type" => "date",
													 "tabindex"=>"7",
								           "obligatoire" => "1",
								           "nom" => "date_entree"),
  "date_sortie" =>  	  Array( "type" => "date",
													 "tabindex"=>"8",
								           "obligatoire" => "0",
								           "nom" => "date_sortie"),
  "sixieme" => 		      Array( "type" => "checkbox",
													 "tabindex"=>"9",
								           "nom" => "sixieme"),
  "recevoir_email_pere" => 	  Array( "type" => "checkbox",
															"tabindex"=>"19",
								           "nom" => "recevoir_email_pere"),
  "recevoir_email_mere" => 	  Array( "type" => "checkbox",
															"tabindex"=>"30",
								           "nom" => "recevoir_email_mere"),
  "infos_compl" =>  	  Array( "type" => "texte",
								           "obligatoire" => "0",
								           "largeur" => "100",
															"tabindex"=>"65",
								           "hauteur" => "7",
								           "nom" => "infos_compl"),
  "derniere_connexion" => 		    Array( "type" => "single",
								           "nom" => "derniere_connexion",
								           "obligatoire" => "0",
								           "longueur" => "10"),
);

$tableau_recherche['eleves'] = Array(
  "nom" => 				  Array( "type" => "varchar",
								           "nom" => "nom",
													 "recherche" => "1",
													 "tabindex"=>"1",
								           "longueur" => "255"),
  'niveaux' => 		Array('type' => 'liste_bdd',
											  'recherche'=>'3',
												'option_vide'=>"1",
												'option' => 'valeur',
												'nom' => 'niveaux',
													 "tabindex"=>"2",
												'nomliste' => 'niveaux'),
  "date_naissance" =>     Array( "type" => "date",
													 "recherche" => "4",
													 "tabindex"=>"3",
								           "nom" => "date_naissance"),
  "sexe" =>               Array( "type" => "liste",
																"nom" => "sexe",
																'option' => 'valeur',
																'option_vide'=>"1",
																"recherche" => "5",
													 "tabindex"=>"4",
																"nomliste" => "sexe"),
  "date_entree" =>        Array( "type" => "date",
													 "recherche" => "6",
													 "tabindex"=>"5",
								           "nom" => "date_entree"),
  "date_sortie" =>  	  Array( "type" => "date",
													 "recherche" => "7",
													 "tabindex"=>"6",
								           "nom" => "date_sortie"),
  "tel_pere" => 		  Array( "type" => "varchar",
							               "nom" => "tel_pere",
															"recherche" => "8",
															"tabindex"=>"9",
							               "longueur" => "50"),
  "tel2_pere" => 		  Array( "type" => "varchar",
							               "nom" => "tel2_pere",
															"tabindex"=>"10",
															"recherche" => "9",
							               "longueur" => "50"),
  "portable_pere" => 	  Array( "type" => "varchar",
							               "nom" => "portable_pere",
															"recherche" => "11",
															"tabindex"=>"11",
							               "longueur" => "50"),
  "tel_mere" => 		  Array( "type" => "varchar",
							               "nom" => "tel_mere",
														"recherche" => "11",
															"tabindex"=>"12",
							               "longueur" => "50"),
  "tel2_mere" => 		  Array( "type" => "varchar",
							               "nom" => "tel2_mere",
														"recherche" => "12",
															"tabindex"=>"13",
							               "longueur" => "50"),
  "portable_mere" => 	  Array( "type" => "varchar",
							               "nom" => "portable_mere",
													 "recherche" => "13",
															"tabindex"=>"14",
							               "longueur" => "50"),
  "assurance_rc" => 	  Array( "type" => "varchar",
								           "nom" => "assurance_rc",
													 "recherche" => "14",
													 "tabindex"=>"8",
								           "longueur" => "255"),
  "assurance_ia" => 	  Array( "type" => "varchar",
								           "nom" => "assurance_ia",
													 "tabindex"=>"7",
													 "recherche" => "15",
								           "longueur" => "255"),
  "identifiant" =>   	  Array( "type" => "varchar",
								           "nom" => "identifiant",
															"tabindex"=>"15",
													 "recherche" => "16",
								           "longueur" => "100"),
);
?>