<?php
$tableau_variable['bibliotheque'] = Array(
  "id" => 		Array(  "type" => "single",
						"nom" => "id",
						"obligatoire" => "0",
						"longueur" => "20"),
  "id_cat" =>   Array(  "type" => "liste_prof",
					    "nom" => "id_cat",
					    "obligatoire" => "0",
					    "longueur" => "10",
					    "partie" => "1",
							"tabindex" => "5",
					    "nomliste" => "categ_biblio_classe"),
  "id_prof" => 	Array(  "type" => "single",
					    "nom" => "id_prof",
						"obligatoire" => "0",
						"longueur" => "5"),
  "reference" =>Array(  "type" => "varchar",
						"nom" => "reference",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"tabindex" => "2",
						"longueur" => "20"),
  "isbn" =>	Array(  "type" => "varchar",
						"nom" => "isbn",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"tabindex" => "6",
						"longueur" => "17"),
  "titre" => 	Array(  "type" => "varchar",
						"nom" => "titre",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"tabindex" => "3",
						"longueur" => "255"),
  "resume" =>  	Array(  "type" => "texte",
						"obligatoire" => "0",
						"largeur" => "100",
						"hauteur" => "8",
						"tabindex" => "10",
						"nom" => "resume"),
  "couverture" => 	Array(  "type" => "varchar",
							"nom" => "couverture",
							"majuscule"=>"0",
							"obligatoire" => "0",
							"tabindex" => "9",
							"longueur" => "255"),
  "editeur" => 		Array(  "type" => "varchar",
							"nom" => "editeur",
							"majuscule"=>"0",
							"obligatoire" => "0",
							"tabindex" => "7",
							"longueur" => "100"),
  "collection" => 	Array(  "type" => "varchar",
							"nom" => "collection",
							"majuscule"=>"0",
							"tabindex" => "8",
							"obligatoire" => "0",
							"longueur" => "100"),
  "auteur" => 	Array(  "type" => "varchar",
						"nom" => "auteur",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"tabindex" => "4",
						"longueur" => "255"),
  "etat" => 	Array( 	"type" => "liste",
						"obligatoire"=>"0",
						"nom" => "etat",
						"tabindex" => "10",
						"nomliste" => "etat_livre"),
);  

$tableau_variable['bibliotheque_ecole'] = Array(
  "id" => 		Array(  "type" => "single",
						"nom" => "id",
						"obligatoire" => "0",
						"longueur" => "20"),
  "id_cat" =>   Array(  "type" => "liste_bdd",
					    "nom" => "id_cat",
					    "obligatoire" => "0",
					    "longueur" => "10",
					    "nomliste" => "categ_biblio_ecole"),
  "id_prof" => 	Array(  "type" => "single",
					    "nom" => "id_prof",
						"obligatoire" => "0",
						"longueur" => "5"),
  "reference" =>Array(  "type" => "varchar",
						"nom" => "reference",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"longueur" => "20"),
  "isbn" =>	    Array(  "type" => "varchar",
						"nom" => "isbn",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"longueur" => "17"),
  "titre" => 	Array(  "type" => "varchar",
						"nom" => "titre",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"longueur" => "255"),
  "resume" =>  	Array(  "type" => "texte",
						"obligatoire" => "0",
						"largeur" => "100",
						"hauteur" => "7",
						"nom" => "resume"),
  "couverture" => 	Array(  "type" => "varchar",
							"nom" => "couverture",
							"majuscule"=>"0",
							"obligatoire" => "0",
							"longueur" => "255"),
  "editeur" => 		Array(  "type" => "varchar",
							"nom" => "editeur",
							"majuscule"=>"0",
							"obligatoire" => "0",
							"longueur" => "100"),
  "collection" => 	Array(  "type" => "varchar",
							"nom" => "collection",
							"majuscule"=>"0",
							"obligatoire" => "0",
							"longueur" => "100"),
  "auteur" => 	Array(  "type" => "varchar",
						"nom" => "auteur",
						"majuscule"=>"0",
						"obligatoire" => "1",
						"longueur" => "255"),
  "etat" => 	Array( 	"type" => "liste",
						"obligatoire"=>"0",
						"nom" => "etat",
						"nomliste" => "etat_livre"),
);

$tableau_recherche['biblio'] = Array(
  "bibliotheque" => 	Array( 	"type" => "liste",
						"recherche" => "0",
						"nom" => "bibliotheque",
						"option" => "valeur",
						"option_vide" => "0",
						"tabindex"=>"1",
						"nomliste" => "liste_biblio_recherche"),
  "categorie" =>   Array(  "type" => "varchar",
					    "nom" => "categorie",
							"recherche" => "1",
						"tabindex"=>"2",
					    "longueur" => "10"),
  "reference" =>Array(  "type" => "varchar",
						"nom" => "reference",
						"recherche" => "2",
						"tabindex"=>"3",
						"longueur" => "20"),
  "titre" => 	Array(  "type" => "varchar",
						"nom" => "titre",
						"recherche" => "3",
						"tabindex"=>"4",
						"longueur" => "255"),
  "auteur" => 	Array(  "type" => "varchar",
						"nom" => "auteur",
						"recherche" => "4",
						"tabindex"=>"5",
						"longueur" => "255"),
  "editeur" => 		Array(  "type" => "varchar",
							"nom" => "editeur",
							"recherche" => "5",
						"tabindex"=>"6",
							"longueur" => "100"),
  "collection" => 	Array(  "type" => "varchar",
							"nom" => "collection",
							"recherche" => "6",
						"tabindex"=>"7",
							"longueur" => "100"),
  "emprunteur" => 	Array(  "type" => "varchar",
							"nom" => "emprunteur",
							"recherche" => "7",
						"tabindex"=>"8",
							"longueur" => "255"),
  "isbn" =>	Array(  "type" => "varchar",
						"nom" => "isbn",
						"recherche" => "8",
						"tabindex"=>"9",
						"longueur" => "17"),
  "etat" => 	Array( 	"type" => "liste",
						"recherche" => "9",
						"nom" => "etat",
						"option" => "valeur",
						"tabindex"=>"10",
						"option_vide" => "0",
						"nomliste" => "etat_livre")
);
?>